INSERT INTO [dbo].[dishes_types] (id,name)
VALUES
  (1,'vitae'),
  (2,'mus.'),
  (3,'magna'),
  (4,'neque'),
  (5,'interdum.'),
  (6,'nunc'),
  (7,'habitant'),
  (8,'eu'),
  (9,'Morbi'),
  (10,'dapibus');
INSERT INTO [dbo].[dishes_types] (id,name)
VALUES
  (11,'euismod'),
  (12,'Pellentesque'),
  (13,'porttitor'),
  (14,'cursus'),
  (15,'sed'),
  (16,'aliquet,'),
  (17,'Etiam'),
  (18,'placerat,'),
  (19,'et'),
  (20,'lobortis');
INSERT INTO [dbo].[dishes_types] (id,name)
VALUES
  (21,'mattis'),
  (22,'ut'),
  (23,'sociis'),
  (24,'non'),
  (25,'leo,'),
  (26,'est'),
  (27,'tincidunt.'),
  (28,'Proin'),
  (29,'elit'),
  (30,'sociis');
INSERT INTO [dbo].[dishes_types] (id,name)
VALUES
  (31,'sollicitudin'),
  (32,'porttitor'),
  (33,'gravida'),
  (34,'Nam'),
  (35,'aliquet'),
  (36,'nec,'),
  (37,'sodales'),
  (38,'semper'),
  (39,'Sed'),
  (40,'Vivamus');
INSERT INTO [dbo].[dishes_types] (id,name)
VALUES
  (41,'Sed'),
  (42,'purus.'),
  (43,'Sed'),
  (44,'Sed'),
  (45,'et,'),
  (46,'vestibulum'),
  (47,'Vivamus'),
  (48,'nec'),
  (49,'pellentesque'),
  (50,'imperdiet');
