/** 
 * file: FillDatabase-Restaurants.sql
 * project: MA-08 Modele Restaurants
 * author: Jeffrey Mvutu Mabilama
 *         Nithujan Jegatheeswaran
 * created: 18.01.2022
 * version: 0.1 based on MLD 1.5


/**
 * 
 * Data generated using RedGate's Compliant Database DevOps tool.
 * The database is created using their plugin SQL Data Generator.
 * 
 * As we discussed about issues encountered by different teams
 * we considered this tool to be great at checking that our assumptions
 * were correct.
 * For instance: checking the data insertion sequence,
 *      checking that the model does not loop, etc.
 * 
 * This specific file has been re-exported as "Data only" from SSMS
 * in order to share the data between the team members.
 */


 /** 
  */


USE [db_restaurants]
GO



INSERT [dbo].[sales] ([id], [name]) 
      VALUES
            (1, N'Soldes Noel'),
            (2, N'Soldes été'),
            (3, N'Nouvel an chinois'),
            (4, N'Black Friday'),

            (5, N'Alvin66'),
            (6, N'Everett252'),
            (7, N'Tonia'),
            (8, N'Jim'),
            (9, N'Erick861'),
            (10, N'Lori9'),
            (11, N'Rogelio248'),
            (12, N'Mason466'),
            (13, N'Christi'),
            (14, N'Mason'),
            (15, N'Hector'),
            (16, N'Melody416'),
            (17, N'Angelica100'),
            (18, N'Randi673'),
            (19, N'Bobbie'),
            (20, N'Rose'),
            (21, N'Beverly21'),
            (22, N'Fernando066'),
            (23, N'Ronda'),
            (24, N'Brad78'),
            (25, N'Dan543'),
            (26, N'Frances'),
            (27, N'Pamela83'),
            (28, N'Alissa'),
            (29, N'Jeffrey99'),
            (30, N'Julie055'),
            (31, N'Darrin'),
            (32, N'Penny1'),
            (33, N'Margarita05'),
            (34, N'Kim78'),
            (35, N'Raymond4'),
            (36, N'Kirsten527'),
            (37, N'Mike02'),
            (38, N'Patricia80'),
            (39, N'Jamison63'),
            (40, N'Leroy736'),
            (41, N'Sabrina74'),
            (42, N'Max51'),
            (43, N'Christa251'),
            (44, N'Bradford2'),
            (45, N'Gordon4'),
            (46, N'Maureen30'),
            (47, N'Tyson757'),
            (48, N'Alisa9'),
            (49, N'Lakesha850'),
            (50, N'Veronica08')
GO




INSERT [dbo].[allergens] ([id], [name], [description])
    VALUES
        (1, N'Confections', N'Multum venit. quad nomen estis nomen et et Sed Id estum. quo Id Quad et regit, quantare quad quartu Et'),
        (2, N'Beverages', N'Longam, eggredior. quartu volcans plurissimum in Pro quad travissimantor Pro nomen quad linguens Longam, travissimantor cognitio,'),
        (3, N'Poultry', N'linguens vobis novum funem. trepicandor plorum eudis e Longam, e esset delerium. fecit. volcans quis'),
        (4, N'Produce', N'fecit. et Et et in plorum Longam, habitatio Et gravum Pro si fecit, habitatio quis trepicandor quoque imaginator fecit. estum.'),
        (5, N'Cereals', N'gravum quad et gravis imaginator nomen essit. vantis. et essit. Multum ut in pladior et quad Pro quartu'),
        (6, N'Meat', N'fecit, Versus imaginator novum plurissimum volcans cognitio, pars et non gravum e ut dolorum egreddior e'),
        (7, N'Seafood', N'quartu e Multum plorum sed rarendum novum egreddior Longam, nomen quad apparens in in Longam, Tam quis manifestum Multum gravis'),
        (8, N'Snails', N'glavans e in quoque habitatio et essit. in non plorum non ut Versus et essit. rarendum imaginator imaginator et quad volcans'),
        (9, N'Beverages', N'parte pars linguens egreddior esset Quad eudis estis quoque venit. gravis quo quantare Sed egreddior'),
        (10, N'Cereals', N'vobis ut Id travissimantor quad Multum et et Sed gravum sed quad nomen novum quad pladior estum. habitatio Quad homo,'),
        (11, N'Dairy', N'e fecit, vobis Et in quoque in e parte et nomen Versus transit. trepicandor vantis. essit. linguens Multum'),
        (12, N'Confections', N'habitatio quo gravum non vobis Sed fecit, si quad quad rarendum quad habitatio homo, linguens esset Quad travissimantor'),
        (13, N'Seafood', N'novum fecundio, et volcans gravis Id travissimantor ut et plorum Versus in manifestum Versus quis bono eggredior. plorum fecundio, non'),
        (14, N'Snails', N'plorum bono funem. imaginator nomen travissimantor non e gravis si si Tam volcans glavans vobis habitatio rarendum habitatio funem. habitatio'),
        (15, N'Cereals', N'Et fecit, si parte cognitio, cognitio, eudis ut quis et plorum non non homo, quo cognitio, nomen gravis Versus'),
        (16, N'Cereals', N'dolorum non plorum eggredior. gravum imaginator transit. esset et pars quoque trepicandor fecundio, Sed si travissimantor'),
        (17, N'Seafood', N'non quad nomen cognitio, fecundio, Longam, manifestum pladior travissimantor non plorum vobis quad volcans'),
        (18, N'Grain', N'Tam novum quad e volcans Versus eudis gravis si quartu Id quad delerium. essit. Longam, sed Multum cognitio,'),
        (19, N'Cereals', N'travissimantor quo e fecit, nomen transit. imaginator in nomen gravum in linguens novum imaginator estis non quo dolorum plorum'),
        (20, N'Cereals', N'non plorum estis estis glavans Longam, homo, Multum bono plorum vantis. quis imaginator si gravum funem. si parte'),
        (21, N'Snails', N'gravum travissimantor fecit, Quad estis quad non egreddior in travissimantor egreddior nomen apparens'),
        (22, N'Beverages', N'manifestum plorum non non si esset quad e et brevens, rarendum manifestum linguens fecit. habitatio trepicandor Sed in'),
        (23, N'Beverages', N'plorum non quis gravis non et quo plorum fecit, quorum regit, non Pro imaginator delerium. in Multum fecit,'),
        (24, N'Meat', N'nomen ut eggredior. nomen gravis estis estum. Sed linguens transit. habitatio fecundio, novum fecit. linguens'),
        (25, N'Produce', N'parte gravum e fecit. linguens novum et quad in vobis eudis essit. pars Pro e plorum sed non delerium. delerium. pars plurissimum non sed brevens,'),
        (26, N'Beverages', N'travissimantor quoque trepicandor trepicandor plurissimum Et gravis transit. non manifestum e transit. nomen fecit.'),
        (27, N'Produce', N'Id quis quad ut novum quartu brevens, sed brevens, novum et fecit. bono rarendum e regit, parte vantis. trepicandor manifestum glavans dolorum Quad'),
        (28, N'Seafood', N'estum. funem. Multum quad in quantare linguens gravis non et plurissimum vobis quad nomen brevens, pars e'),
        (29, N'Shell fish', N'vobis quantare Pro quad eggredior. vobis Quad vobis nomen egreddior delerium. in quo novum esset pars rarendum fecundio, Tam in quantare et gravum'),
        (30, N'Shell fish', N'quantare fecit, esset et et non venit. et si gravis et trepicandor quo eggredior. quartu trepicandor quis fecit. non venit. eudis'),
        (31, N'Grain', N'novum delerium. et vantis. Quad non Longam, essit. glavans vantis. non vobis vantis. e fecit. transit.'),
        (32, N'Cereals', N'et quorum parte quoque estis egreddior quo quantare brevens, sed quo estum. ut quad in e plurissimum'),
        (33, N'Cereals', N'plurissimum cognitio, si linguens estum. rarendum quo, ut manifestum non novum quantare sed quorum non quo'),
        (34, N'Dairy', N'apparens e si plorum vobis Quad dolorum glavans glavans si Sed si regit, essit. venit. Sed novum novum'),
        (35, N'Snails', N'bono quantare et vobis plorum Id fecit, et homo, Id venit. plurissimum habitatio vantis. venit. si novum non'),
        (36, N'Produce', N'esset vobis regit, imaginator vobis eudis Multum plorum Tam et e apparens Versus dolorum fecundio, plorum gravis'),
        (37, N'Shell fish', N'plorum Et vobis rarendum glavans pars Longam, travissimantor egreddior in estum. Et quad novum essit.'),
        (38, N'Dairy', N'fecit, Tam ut non non quad gravis si brevens, Quad vantis. non quo esset non ut trepicandor quantare'),
        (39, N'Poultry', N'novum rarendum manifestum et nomen linguens novum eudis cognitio, esset vantis. ut plorum sed novum pladior'),
        (40, N'Poultry', N'in Quad quo, esset e si cognitio, si quo si parte estis linguens Quad homo, habitatio ut quis in et gravis'),
        (41, N'Seafood', N'essit. habitatio vantis. Pro novum delerium. novum eggredior. quorum gravis ut quantare quis et vobis'),
        (42, N'Snails', N'parte gravis imaginator brevens, vobis Multum funem. volcans esset homo, fecit. sed Versus vobis et trepicandor pladior volcans'),
        (43, N'Cereals', N'plorum parte imaginator quantare rarendum travissimantor Sed plorum eggredior. essit. travissimantor'),
        (44, N'Meat', N'plurissimum estum. Quad et estum. homo, homo, quo nomen regit, non quoque quoque quantare eggredior.'),
        (45, N'Meat', N'regit, fecit, vantis. brevens, et transit. novum quoque transit. vobis quis Et vobis quo novum Sed et'),
        (46, N'Cereals', N'plurissimum gravis quo et estum. ut quorum quo vobis regit, esset Quad quad parte e transit. quis si quo plurissimum si'),
        (47, N'Cereals', N'Versus quoque linguens estum. regit, si trepicandor quad Et in si gravis travissimantor venit. trepicandor'),
        (48, N'Poultry', N'Quad plorum nomen volcans e si estum. quartu regit, quo, quad rarendum rarendum fecundio, transit. quo apparens'),
        (49, N'Confections', N'quantare quo, quad brevens, novum cognitio, e fecit. non pladior delerium. volcans egreddior manifestum')
GO


INSERT [dbo].[dishes_types] ([id], [name])
    VALUES
        (1, N'quad trepicandor rarendum quo non Pro'),
        (2, N'brevens, non linguens cognitio,'),
        (3, N'estis trepicandor estum. travissimantor'),
        (4, N'homo, et travissimantor non transit.'),
        (5, N'nomen quad esset pladior Sed non esset'),
        (6, N'Versus et quantare Sed novum Multum'),
        (7, N'trepicandor ut egreddior trepicandor'),
        (8, N'essit. transit. Multum Sed esset venit.'),
        (9, N'pladior quad si quad habitatio estis'),
        (10, N'Sed et et rarendum gravis in vantis.'),
        (11, N'linguens novum Tam quartu bono essit.'),
        (12, N'fecit, Longam, linguens Sed gravum'),
        (13, N'nomen bono quo, egreddior parte glavans'),
        (14, N'quorum e esset quad estis estum. plorum'),
        (15, N'dolorum sed et nomen transit. fecundio,'),
        (16, N'rarendum et essit. non et et pars'),
        (17, N'Sed nomen novum imaginator essit. e'),
        (18, N'Multum quoque fecit, trepicandor plorum'),
        (19, N'gravis ut gravis cognitio, e essit.'),
        (20, N'delerium. plorum Pro gravum linguens'),
        (21, N'linguens delerium. brevens, plorum'),
        (22, N'et venit. cognitio, quo, quo et sed'),
        (23, N'eggredior. gravum non brevens, vobis quo'),
        (24, N'essit. plorum nomen vobis bono in plorum'),
        (25, N'dolorum pladior habitatio estis quoque'),
        (26, N'novum linguens cognitio, Quad rarendum'),
        (27, N'in non pladior plurissimum trepicandor'),
        (28, N'et sed cognitio, sed gravum egreddior'),
        (29, N'si eudis imaginator habitatio quis Sed'),
        (30, N'brevens, e egreddior quorum novum gravis'),
        (31, N'essit. habitatio Id quad delerium. Quad'),
        (32, N'funem. sed quad e novum manifestum nomen'),
        (33, N'non quis Multum in fecundio, pladior'),
        (34, N'venit. fecit. et nomen Versus pladior'),
        (35, N'Pro quoque e gravis cognitio, fecit,'),
        (36, N'plorum fecit, ut Id glavans nomen'),
        (37, N'imaginator regit, glavans ut nomen si'),
        (38, N'plorum e sed habitatio Quad Longam,'),
        (39, N'fecit. eggredior. habitatio gravis estis'),
        (40, N'ut linguens si homo, delerium. cognitio,'),
        (41, N'quo, habitatio in quad Et nomen e gravum'),
        (42, N'esset Tam delerium. imaginator pars'),
        (43, N'fecit. fecit, brevens, pars e non sed'),
        (44, N'e eudis esset estis novum Longam, Versus'),
        (45, N'vobis et et trepicandor brevens, quo,'),
        (46, N'quo ut et Quad et trepicandor'),
        (47, N'dolorum non plorum eggredior. pars et'),
        (48, N'Multum volcans et plurissimum e'),
        (49, N'pars in quad glavans quorum quad Longam,'),
        (50, N'fecit, gravis estis et esset egreddior')
GO


INSERT INTO [dbo].[measurement_units] (id,name)
VALUES
  (1,'cm'),
  (2,'ml'),
  (3,'g'),
  (4,'cs'),
  (5,'cc');
GO


INSERT [dbo].[locations] ([id], [city], [ZIP])
    VALUES
        (1, N'Chicago', 1110),
        (2, N'Lubbock', 1033),
        (3, N'Philadelphia', 1150),
        (4, N'Milwaukee', 1076),
        (5, N'Louisville', 1007),
        (6, N'St. Petersburg', 1107),
        (7, N'El Paso', 1133),
        (8, N'Oklahoma', 1159),
        (9, N'El Paso', 1068),
        (10, N'Nashville', 1124),
        (11, N'Buffalo', 1047),
        (12, N'Little Rock', 1148),
        (13, N'Los Angeles', 1142),
        (14, N'Tulsa', 1192),
        (15, N'Kansas', 1001),
        (16, N'Akron', 1067),
        (17, N'Bakersfield', 1078),
        (18, N'Dayton', 1102),
        (19, N'Chicago', 1010),
        (20, N'Riverside', 1015),
        (21, N'Kansas', 1088),
        (22, N'Honolulu', 1138),
        (23, N'Santa Ana', 1140),
        (24, N'Richmond', 1022),
        (25, N'Tacoma', 1008),
        (26, N'Greensboro', 1106),
        (27, N'Washington', 1009),
        (28, N'Memphis', 1160),
        (29, N'Lubbock', 1030),
        (30, N'Los Angeles', 1165),
        (31, N'Jackson', 1030),
        (32, N'Phoenix', 1070),
        (33, N'Charlotte', 1150),
        (34, N'Philadelphia', 1014),
        (35, N'St. Louis', 1139),
        (36, N'Dallas', 1023),
        (37, N'New Orleans', 1013),
        (38, N'Washington', 1175),
        (39, N'Riverside', 1172),
        (40, N'San Jose', 1135),
        (41, N'Arlington', 1153),
        (42, N'Tacoma', 1044),
        (43, N'Bakersfield', 1107),
        (44, N'Rochester', 1156),
        (45, N'Shreveport', 1060),
        (46, N'Tucson', 1041),
        (47, N'Arlington', 1067),
        (48, N'Aurora', 1148),
        (49, N'Fresno', 1115),
        (50, N'Pittsburgh', 1107),
        (51, N'Tucson', 1090),
        (52, N'Austin', 1145),
        (53, N'Colorado', 1054),
        (54, N'Oakland', 1119),
        (55, N'Birmingham', 1162),
        (56, N'Louisville', 1173),
        (57, N'Charlotte', 1094),
        (58, N'Oklahoma', 1127),
        (59, N'El Paso', 1067),
        (60, N'Anchorage', 1102),
        (61, N'Fresno', 1097),
        (62, N'Houston', 1173),
        (63, N'Sacramento', 1129),
        (64, N'Boston', 1104),
        (65, N'Miami', 1093),
        (66, N'Sacramento', 1178),
        (67, N'Birmingham', 1198),
        (68, N'Fremont', 1127),
        (69, N'San Antonio', 1053),
        (70, N'Cleveland', 1179),
        (71, N'Fresno', 1054),
        (72, N'Jackson', 1103),
        (73, N'Seattle', 1131),
        (74, N'Glendale', 1075),
        (75, N'Riverside', 1062),
        (76, N'Atlanta', 1043),
        (77, N'Omaha', 1031),
        (78, N'Montgomery', 1184),
        (79, N'Arlington', 1163),
        (80, N'Arlington', 1167),
        (81, N'Dayton', 1038),
        (82, N'Miami', 1062),
        (83, N'Anchorage', 1045),
        (84, N'Fresno', 1124),
        (85, N'Jersey', 1074),
        (86, N'Wichita', 1086),
        (87, N'Colorado', 1016),
        (88, N'Little Rock', 1031),
        (89, N'Honolulu', 1053),
        (90, N'Richmond', 1166),
        (91, N'Baton Rouge', 1130),
        (92, N'Little Rock', 1086),
        (93, N'Fremont', 1108),
        (94, N'Fort Wayne', 1070),
        (95, N'Las Vegas', 1038),
        (96, N'Bakersfield', 1180),
        (97, N'Santa Ana', 1116),
        (98, N'Richmond', 1002),
        (99, N'Boston', 1063),
        (100, N'Atlanta', 1083)
GO


INSERT [dbo].[restaurant_types] ([id], [name], [description]) 
    VALUES
        (1, N'Antonio924', N'Sed novum delerium. quorum linguens et trepicandor novum Quad quo non et novum Versus non Pro Tam quo, plorum quantare'),
        (2, N'Megan8', N'cognitio, novum quad esset quad quartu eudis funem. essit. quartu vobis quartu rarendum vobis plorum'),
        (3, N'Dora2', N'quoque non esset et quantare nomen non plurissimum estis Pro gravis quad et pars homo, vobis Quad pars apparens quartu et'),
        (4, N'Pete1', N'habitatio linguens fecit. vobis essit. quo, gravum non nomen nomen quantare eggredior. vobis quoque et'),
        (5, N'Sherry98', N'regit, rarendum non vobis quo estis brevens, et Id vantis. bono apparens e regit, plurissimum Id imaginator quad'),
        (6, N'Jeff840', N'quad cognitio, vantis. e plurissimum nomen pars Et et gravum quad rarendum plorum vobis habitatio vantis. quorum Tam'),
        (7, N'Tracy474', N'e vobis travissimantor si quis e eudis fecit, quantare vobis eggredior. et estis si quis novum travissimantor'),
        (8, N'Nora163', N'quoque linguens egreddior si vantis. si linguens Versus quad egreddior gravis Longam, quis et egreddior'),
        (9, N'Rachelle43', N'delerium. quoque Quad Quad Sed plurissimum linguens essit. quartu rarendum essit. homo, bono quad linguens trepicandor'),
        (10, N'Laurie', N'Et gravis et Longam, Pro quartu linguens trepicandor novum vobis plorum gravis dolorum linguens Versus'),
        (11, N'Harry385', N'e imaginator et non fecit. manifestum transit. brevens, Tam cognitio, pars et non fecit. plurissimum et'),
        (12, N'Jacquelyn41', N'vantis. et Versus vobis Versus gravum glavans vobis plorum Multum e gravis non quo Quad Tam et in Et fecit.'),
        (13, N'Matt09', N'gravis gravis Pro ut in ut Multum fecit, quorum non nomen quad parte ut venit. fecit. Tam Id quantare non'),
        (14, N'Karen', N'e linguens parte apparens et Multum vobis Pro Versus quis e quo eudis quo Longam, et homo, quad funem.'),
        (15, N'Tameka950', N'nomen Quad pladior gravis linguens novum Id sed quorum fecit. pars vobis quad homo, estis plorum Tam'),
        (16, N'Rochelle0', N'non Id essit. habitatio vantis. et in si quad et quartu linguens plorum glavans novum et essit. si in'),
        (17, N'Joy556', N'quad quo estum. quoque bono quoque rarendum fecit. travissimantor plorum essit. glavans si cognitio,'),
        (18, N'Catherine7', N'e glavans Multum et Id quartu pars eudis delerium. transit. quo, vantis. quis trepicandor e quad homo,'),
        (19, N'Tammie850', N'apparens et essit. quad e Et dolorum non et vobis gravis glavans novum fecit. non non parte eggredior.'),
        (20, N'Norma4', N'cognitio, in e Et eudis homo, plorum eudis Longam, linguens vobis eggredior. Versus estum. novum estum.'),
        (21, N'Elena', N'gravis novum vobis cognitio, delerium. si linguens gravum in si quartu e eudis Tam homo, quo Et quorum quantare'),
        (22, N'Frederick6', N'volcans Et gravum pars eggredior. Pro dolorum non quartu quantare Id nomen et plurissimum plorum vantis.'),
        (23, N'Taryn133', N'imaginator funem. plorum et gravis transit. parte dolorum novum Quad transit. nomen quoque nomen travissimantor'),
        (24, N'Ginger577', N'apparens quorum quad eggredior. gravis et quad novum non Pro et quartu imaginator vantis. quis fecundio, Versus'),
        (25, N'John00', N'pars si volcans habitatio Et trepicandor venit. Id venit. cognitio, Versus non pladior nomen quad quis'),
        (26, N'Todd260', N'pladior plorum non estum. novum et bono et quoque quad gravis quad Pro Tam glavans essit. essit. delerium. nomen fecit.'),
        (27, N'Oscar490', N'vantis. regit, parte et vantis. quartu linguens Tam plurissimum delerium. ut fecit, non gravum Versus non'),
        (28, N'Jack', N'quad quoque quo gravum volcans e novum quad regit, e travissimantor novum et Tam novum funem. Versus'),
        (29, N'Benny4', N'et sed quad quantare funem. cognitio, et e cognitio, quad habitatio vobis regit, plurissimum pars quo rarendum quo,'),
        (30, N'Jami003', N'Longam, novum imaginator bono plorum quartu e novum parte quo et quad si gravis vobis vantis. pladior'),
        (31, N'Alisa323', N'fecit, transit. Tam et quo delerium. si vantis. plorum novum et et gravum transit. apparens quad Et venit.'),
        (32, N'Gerardo2', N'novum non trepicandor nomen quad non et Et si vobis bono linguens esset et e Longam, et si habitatio'),
        (33, N'Cherie92', N'et et e non quad in quad pars bono trepicandor linguens vobis sed linguens vobis quad vantis. cognitio,'),
        (34, N'Lonnie94', N'trepicandor esset habitatio non fecit. quo, novum gravum homo, nomen in estum. vobis plorum estis quartu quis'),
        (35, N'Alvin93', N'fecit. regit, delerium. nomen esset eudis fecit. fecit, Sed quis novum pladior vobis egreddior quartu esset quad'),
        (36, N'Cedric21', N'quo, essit. Et Et estum. et non Pro sed gravis novum fecit, funem. quad gravis trepicandor Longam, eggredior. fecit, ut'),
        (37, N'Jamie7', N'apparens parte essit. rarendum Id venit. nomen glavans parte non novum travissimantor quad non rarendum brevens, quad'),
        (38, N'Megan658', N'gravis regit, homo, in eudis si estum. ut nomen eudis linguens regit, fecit, plurissimum volcans vobis vobis'),
        (39, N'Carolyn6', N'Quad manifestum homo, e novum non Tam et Multum parte gravum imaginator e parte gravum e essit. travissimantor'),
        (40, N'Julio9', N'Quad non Versus quartu quad plurissimum Pro quo Quad e et ut travissimantor fecundio, esset in sed glavans plurissimum gravis transit.'),
        (41, N'Gerardo7', N'Quad trepicandor et quorum et novum nomen et parte estum. novum plorum Id si cognitio, venit. quad volcans'),
        (42, N'Grant615', N'e fecundio, Et e quantare fecit, pars Id vobis plorum eggredior. volcans homo, esset nomen esset non'),
        (43, N'Clayton', N'fecundio, vobis quo nomen dolorum plorum et novum Multum sed Quad estis Tam habitatio quantare Versus non'),
        (44, N'Teresa690', N'glavans plorum regit, novum nomen quo quantare e quo non quad travissimantor novum brevens, pars et estum.'),
        (45, N'Teresa8', N'fecit, volcans Sed cognitio, et venit. Longam, funem. Id quorum et non Quad homo, bono Sed gravis quorum'),
        (46, N'Jared775', N'plurissimum sed bono trepicandor et linguens homo, habitatio quo non regit, Longam, non non fecundio,'),
        (47, N'Ruby570', N'non vantis. et funem. in si plurissimum non ut travissimantor cognitio, dolorum quad quad quad quorum nomen Longam, non manifestum'),
        (48, N'Dina82', N'quo novum nomen quartu estis non ut non et Quad eudis plorum si venit. non essit. quis quantare cognitio,'),
        (49, N'Martin92', N'quorum et gravum Et plurissimum manifestum esset transit. Sed quis Id gravis pars ut eudis esset funem.'),
        (50, N'Alexander', N'vobis non quo, quartu et quartu fecit. essit. Versus volcans quad quo, homo, quad quad glavans Multum')
GO


INSERT [dbo].[dishes] ([id], [name], [description], [base_price], [sale_price], [dish_type_id])
    VALUES
        (1, N'Beverages', N'in gravum bono cognitio, fecit. Pro quad delerium. regit, plurissimum Id et quo quartu travissimantor linguens in novum', CAST(1840.84 AS Decimal(6, 2)), CAST(7065.09 AS Decimal(6, 2)), 727),
        (2, N'Poultry', N'Quad Pro si dolorum non gravis delerium. egreddior linguens quad quo, imaginator eudis nomen et nomen et', CAST(795.74 AS Decimal(6, 2)), CAST(3729.93 AS Decimal(6, 2)), 818),
        (3, N'Produce', N'manifestum volcans homo, Versus in fecit, gravis bono Quad quoque fecit, dolorum manifestum quantare vobis sed', CAST(1560.93 AS Decimal(6, 2)), CAST(8550.81 AS Decimal(6, 2)), 769),
        (4, N'Poultry', N'pars plorum transit. rarendum Multum brevens, trepicandor et sed sed quo, manifestum quad Quad fecit, estis', CAST(8951.72 AS Decimal(6, 2)), CAST(1086.15 AS Decimal(6, 2)), 559),
        (5, N'Grain', N'et Et e quad essit. estis vantis. plorum e cognitio, e gravis sed brevens, quis gravis novum habitatio gravis', CAST(5246.82 AS Decimal(6, 2)), CAST(9761.68 AS Decimal(6, 2)), 207),
        (6, N'Dairy', N'gravum Pro et volcans manifestum fecit. plurissimum pars quad plorum non habitatio volcans ut delerium. brevens, plorum', CAST(7946.40 AS Decimal(6, 2)), CAST(6685.38 AS Decimal(6, 2)), 4),
        (7, N'Produce', N'essit. Longam, vobis bono Longam, Id quis homo, quartu non esset estum. manifestum Id funem. quad estis', CAST(6803.72 AS Decimal(6, 2)), CAST(1284.28 AS Decimal(6, 2)), 907),
        (8, N'Beverages', N'quad linguens venit. et eggredior. estis quad brevens, plurissimum quis si quorum e fecundio, plorum', CAST(1217.16 AS Decimal(6, 2)), CAST(6234.00 AS Decimal(6, 2)), 443),
        (9, N'Beverages', N'bono bono esset linguens quoque manifestum e dolorum Longam, si Pro quo, gravum in egreddior quorum gravum', CAST(4064.03 AS Decimal(6, 2)), CAST(5301.20 AS Decimal(6, 2)), 978),
        (10, N'Meat', N'et brevens, essit. estis eudis quad regit, Quad non transit. fecit, vobis quantare fecit. in travissimantor linguens non Tam manifestum', CAST(1833.29 AS Decimal(6, 2)), CAST(5520.80 AS Decimal(6, 2)), 274),
        (11, N'Confections', N'e apparens manifestum linguens Pro non Quad dolorum transit. estum. quo si Longam, et e in linguens plorum', CAST(7382.79 AS Decimal(6, 2)), CAST(4750.10 AS Decimal(6, 2)), 292),
        (12, N'Grain', N'funem. pars novum brevens, habitatio quad Longam, quantare non gravis quantare pladior et fecit, esset trepicandor quorum', CAST(1642.33 AS Decimal(6, 2)), CAST(9449.48 AS Decimal(6, 2)), 468),
        (13, N'Beverages', N'homo, in gravis sed novum quo habitatio vantis. gravis eudis habitatio egreddior quo imaginator ut pladior', CAST(5446.65 AS Decimal(6, 2)), CAST(2321.16 AS Decimal(6, 2)), 633),
        (14, N'Confections', N'gravis vantis. non et si plorum pars regit, gravis manifestum si travissimantor Multum habitatio estis et', CAST(2544.64 AS Decimal(6, 2)), CAST(7747.20 AS Decimal(6, 2)), 470),
        (15, N'Snails', N'brevens, quorum quoque rarendum cognitio, plorum vobis quad Pro pars trepicandor habitatio quad linguens', CAST(3956.38 AS Decimal(6, 2)), CAST(956.10 AS Decimal(6, 2)), 983),
        (16, N'Confections', N'plorum quis novum rarendum cognitio, transit. quad habitatio quo, non estis fecundio, Quad parte e Tam', CAST(4321.23 AS Decimal(6, 2)), CAST(566.43 AS Decimal(6, 2)), 31),
        (17, N'Grain', N'fecundio, quantare venit. linguens quoque brevens, habitatio et bono linguens Versus transit. eggredior. funem.', CAST(4665.10 AS Decimal(6, 2)), CAST(8868.69 AS Decimal(6, 2)), 863),
        (18, N'Confections', N'et vantis. linguens gravum imaginator gravis e manifestum Pro estis fecundio, plorum transit. delerium.', CAST(4932.77 AS Decimal(6, 2)), CAST(1132.77 AS Decimal(6, 2)), 996),
        (19, N'Shell fish', N'et esset Multum si habitatio rarendum novum eudis egreddior gravum homo, quad non quorum habitatio quad', CAST(9186.19 AS Decimal(6, 2)), CAST(9456.89 AS Decimal(6, 2)), 678),
        (20, N'Confections', N'delerium. habitatio pars gravis plorum Versus vobis trepicandor e dolorum Id et novum nomen pladior parte apparens', CAST(9696.05 AS Decimal(6, 2)), CAST(3568.10 AS Decimal(6, 2)), 315),
        (21, N'Beverages', N'plorum plorum si Quad estis apparens fecit, Id essit. et venit. vobis et eudis glavans linguens bono dolorum eudis Id', CAST(3938.12 AS Decimal(6, 2)), CAST(5266.83 AS Decimal(6, 2)), 817),
        (22, N'Produce', N'quo nomen et e plurissimum egreddior venit. fecit, novum non habitatio quad in eudis non venit. et Versus', CAST(2583.96 AS Decimal(6, 2)), CAST(5037.33 AS Decimal(6, 2)), 849),
        (23, N'Seafood', N'et non pladior Versus Tam gravum linguens linguens vobis estis novum Longam, essit. quo Multum in plurissimum cognitio,', CAST(6823.09 AS Decimal(6, 2)), CAST(8513.14 AS Decimal(6, 2)), 992),
        (24, N'Grain', N'quad nomen Sed eudis apparens glavans quad regit, quo, gravis novum funem. pladior quo, quo, quad quorum quad Multum vobis', NULL, CAST(6205.50 AS Decimal(6, 2)), 33),
        (25, N'Shell fish', N'linguens non Versus gravis plorum gravis homo, gravum travissimantor et imaginator gravis sed et quo, quoque funem. non non', CAST(2712.04 AS Decimal(6, 2)), CAST(1655.16 AS Decimal(6, 2)), 700),
        (26, N'Dairy', N'et quoque non vobis bono nomen Tam Longam, non quad fecit. Longam, non plorum Tam imaginator glavans', CAST(675.10 AS Decimal(6, 2)), CAST(9572.24 AS Decimal(6, 2)), 527),
        (27, N'Snails', N'plurissimum non gravis parte Quad Et ut Sed si eudis nomen quorum vantis. estis volcans si Pro novum', CAST(3140.41 AS Decimal(6, 2)), CAST(5710.47 AS Decimal(6, 2)), 935),
        (28, N'Produce', N'Id eggredior. quantare quo sed estum. plorum et fecit. Et dolorum eggredior. bono non pladior Id transit.', CAST(7112.82 AS Decimal(6, 2)), CAST(6017.04 AS Decimal(6, 2)), 688),
        (29, N'Seafood', N'delerium. quo quad plorum quad parte pladior linguens et non trepicandor bono travissimantor non Et plorum', CAST(9820.96 AS Decimal(6, 2)), CAST(1779.91 AS Decimal(6, 2)), 547),
        (30, N'Snails', N'vobis estis Pro in pars trepicandor gravum quad vobis glavans travissimantor quo regit, parte estis volcans', CAST(9017.78 AS Decimal(6, 2)), CAST(3672.10 AS Decimal(6, 2)), 82),
        (31, N'Cereals', N'nomen et fecit. vobis Et plorum Versus dolorum et gravis eggredior. Versus venit. quartu ut fecundio, novum fecit.', CAST(5618.51 AS Decimal(6, 2)), CAST(7778.57 AS Decimal(6, 2)), 188),
        (32, N'Shell fish', N'plorum fecit. nomen sed estis Longam, quantare fecit, quad estis non quoque esset esset et gravum eggredior.', CAST(4086.80 AS Decimal(6, 2)), CAST(6927.12 AS Decimal(6, 2)), 454),
        (33, N'Dairy', N'quad regit, nomen cognitio, Longam, bono rarendum quartu egreddior et et quoque fecundio, Sed parte quis vantis. Tam rarendum e', CAST(4293.05 AS Decimal(6, 2)), CAST(2304.92 AS Decimal(6, 2)), 298),
        (34, N'Dairy', N'funem. e Et egreddior Et et Multum venit. Sed in gravum quorum plorum quartu quo non pladior quis novum quoque delerium. imaginator et', CAST(8283.68 AS Decimal(6, 2)), CAST(1057.81 AS Decimal(6, 2)), 989),
        (35, N'Cereals', N'essit. imaginator quantare Longam, e pladior non si et nomen dolorum Id Quad homo, e plorum linguens', CAST(807.11 AS Decimal(6, 2)), CAST(7161.43 AS Decimal(6, 2)), 643),
        (36, N'Snails', N'plorum e Pro quad quis linguens cognitio, quis manifestum trepicandor quo et quantare apparens non egreddior', CAST(3669.64 AS Decimal(6, 2)), CAST(707.02 AS Decimal(6, 2)), 763),
        (37, N'Grain', N'quad trepicandor et si e in in egreddior Tam Pro novum et venit. non imaginator dolorum essit. Id quad', CAST(273.64 AS Decimal(6, 2)), CAST(328.60 AS Decimal(6, 2)), 16),
        (38, N'Grain', N'cognitio, quorum Multum dolorum in in volcans quad pars vobis glavans si egreddior in apparens gravis fecit,', CAST(2045.10 AS Decimal(6, 2)), CAST(6713.68 AS Decimal(6, 2)), 382),
        (39, N'Grain', N'quis quo e non Id quo, Sed eggredior. estum. et quantare gravum non egreddior in plurissimum quantare', CAST(9898.69 AS Decimal(6, 2)), CAST(1140.13 AS Decimal(6, 2)), 344),
        (40, N'Produce', N'estum. fecit. brevens, transit. gravum cognitio, homo, bono quad Versus egreddior transit. bono pars delerium. fecit.', CAST(9427.61 AS Decimal(6, 2)), CAST(5197.24 AS Decimal(6, 2)), 958),
        (41, N'Grain', N'vobis estum. ut dolorum novum vobis et e e regit, pladior quad non e quo, brevens, Et plorum gravis ut imaginator novum fecundio, e linguens ut gravis', CAST(9519.21 AS Decimal(6, 2)), CAST(9378.57 AS Decimal(6, 2)), 506),
        (42, N'Poultry', N'Tam rarendum venit. Quad quo e eggredior. esset fecit, quantare rarendum essit. funem. eudis quad in', CAST(1701.61 AS Decimal(6, 2)), CAST(3020.96 AS Decimal(6, 2)), 716),
        (43, N'Seafood', N'volcans parte venit. Sed apparens Pro fecit. egreddior gravis non sed et quantare homo, Quad quad pars', CAST(242.73 AS Decimal(6, 2)), CAST(422.02 AS Decimal(6, 2)), 119),
        (44, N'Dairy', N'nomen cognitio, imaginator manifestum estum. glavans venit. et gravis pars dolorum novum Longam, venit.', CAST(4700.56 AS Decimal(6, 2)), CAST(3659.17 AS Decimal(6, 2)), 10),
        (45, N'Beverages', N'rarendum e egreddior vantis. apparens vantis. gravis eggredior. egreddior funem. habitatio gravis vantis.', CAST(2527.53 AS Decimal(6, 2)), CAST(6849.65 AS Decimal(6, 2)), 908),
        (46, N'Dairy', N'fecundio, eudis cognitio, et Id Pro si Id si pars Pro parte plurissimum nomen Id fecit. quad quis novum', CAST(1577.29 AS Decimal(6, 2)), CAST(6432.09 AS Decimal(6, 2)), 795),
        (47, N'Shell fish', N'non gravum estum. eudis quo et quantare Longam, et ut Sed plorum apparens Pro linguens imaginator nomen Longam,', CAST(7625.69 AS Decimal(6, 2)), CAST(8579.84 AS Decimal(6, 2)), 338),
        (48, N'Grain', N'quo, Quad apparens cognitio, regit, et pladior et eggredior. dolorum venit. linguens regit, quad regit, ut et', CAST(5177.63 AS Decimal(6, 2)), CAST(6455.01 AS Decimal(6, 2)), 458),
        (49, N'Seafood', N'Sed delerium. sed essit. non imaginator Versus volcans vobis trepicandor quad regit, novum brevens, delerium. et', CAST(6298.35 AS Decimal(6, 2)), CAST(6526.74 AS Decimal(6, 2)), 147),
        (50, N'Meat', N'quartu glavans venit. venit. eudis delerium. non regit, et quo Versus vobis et eggredior. quad homo,', CAST(5549.80 AS Decimal(6, 2)), CAST(7743.00 AS Decimal(6, 2)), 222),
        (51, N'Meat', N'et et et brevens, Sed egreddior e quo et fecundio, estis cognitio, bono quoque gravis apparens fecit, quad plurissimum Et', CAST(6421.30 AS Decimal(6, 2)), CAST(7778.05 AS Decimal(6, 2)), 411),
        (52, N'Cereals', N'plorum glavans quis vobis transit. si estum. linguens vobis et plurissimum plorum et quad Quad quartu et linguens gravis', CAST(6616.25 AS Decimal(6, 2)), CAST(733.23 AS Decimal(6, 2)), 719),
        (53, N'Snails', N'e quo pars Versus venit. homo, Longam, et apparens quantare quad regit, egreddior si Sed quo quad plurissimum', CAST(6226.23 AS Decimal(6, 2)), CAST(1259.88 AS Decimal(6, 2)), 620),
        (54, N'Poultry', N'quoque quo quartu manifestum essit. linguens Tam gravis in et si imaginator Longam, trepicandor Longam,', CAST(3992.30 AS Decimal(6, 2)), CAST(1519.49 AS Decimal(6, 2)), 488),
        (55, N'Poultry', N'quad linguens Quad gravis essit. Multum si delerium. quad pars trepicandor estum. et cognitio, e venit.', CAST(9482.22 AS Decimal(6, 2)), CAST(1013.56 AS Decimal(6, 2)), 195),
        (56, N'Meat', N'esset imaginator vobis egreddior regit, quad travissimantor transit. estum. quorum Id Sed in in eggredior.', CAST(9011.27 AS Decimal(6, 2)), CAST(2027.76 AS Decimal(6, 2)), 879),
        (57, N'Beverages', N'quo nomen quad sed bono quad Multum sed estis fecundio, brevens, nomen in Multum apparens fecit. fecundio, travissimantor pars', CAST(9256.87 AS Decimal(6, 2)), CAST(5216.79 AS Decimal(6, 2)), 826),
        (58, N'Confections', N'trepicandor estum. parte gravis homo, novum homo, venit. funem. fecit, Versus e plorum travissimantor', CAST(3972.65 AS Decimal(6, 2)), CAST(2345.31 AS Decimal(6, 2)), 736),
        (59, N'Grain', N'travissimantor gravum e regit, plorum Versus quantare novum sed eggredior. nomen novum Pro in brevens,', CAST(8848.89 AS Decimal(6, 2)), CAST(9430.99 AS Decimal(6, 2)), 859),
        (60, N'Grain', N'quo, eggredior. in quo Longam, volcans fecit. eudis bono fecundio, sed fecit. dolorum Longam, et Sed parte quo', CAST(8276.61 AS Decimal(6, 2)), CAST(189.44 AS Decimal(6, 2)), 680),
        (61, N'Dairy', N'delerium. Quad quartu ut et quad linguens quad pars Sed manifestum in si apparens quo volcans dolorum et quorum nomen Versus gravis', CAST(2106.41 AS Decimal(6, 2)), CAST(974.90 AS Decimal(6, 2)), 625),
        (62, N'Dairy', N'estum. egreddior Et Multum plurissimum transit. plurissimum plurissimum Pro gravum volcans gravum linguens pladior', CAST(833.58 AS Decimal(6, 2)), CAST(5267.24 AS Decimal(6, 2)), 219),
        (63, N'Produce', N'si Tam quantare si vobis novum brevens, Pro fecit. novum egreddior gravum rarendum plurissimum gravis quartu pladior', CAST(6982.75 AS Decimal(6, 2)), CAST(4454.09 AS Decimal(6, 2)), 896),
        (64, N'Confections', N'vobis si non nomen pladior vantis. si plorum Id Id cognitio, quis et Versus trepicandor Sed trepicandor', CAST(2199.38 AS Decimal(6, 2)), CAST(1629.09 AS Decimal(6, 2)), 897),
        (65, N'Produce', N'estum. et Pro fecit, quantare funem. ut quo regit, estis non estis imaginator linguens quorum fecit.', CAST(8445.52 AS Decimal(6, 2)), CAST(7742.22 AS Decimal(6, 2)), 87),
        (66, N'Seafood', N'transit. plorum sed estum. pars Longam, trepicandor essit. pars esset si Longam, volcans non et brevens, quad pladior novum', CAST(7746.49 AS Decimal(6, 2)), CAST(7822.98 AS Decimal(6, 2)), 839),
        (67, N'Grain', N'manifestum e Pro quo travissimantor volcans non esset vobis gravis venit. trepicandor dolorum quad quorum Et vobis non', CAST(3089.74 AS Decimal(6, 2)), CAST(7144.55 AS Decimal(6, 2)), 171),
        (68, N'Beverages', N'travissimantor pladior vobis et regit, quoque et Quad cognitio, vobis manifestum apparens nomen venit.', CAST(3358.64 AS Decimal(6, 2)), CAST(1263.34 AS Decimal(6, 2)), 645),
        (69, N'Poultry', N'e vobis eudis estis Id eudis si funem. in sed quis linguens habitatio quo et travissimantor delerium. esset habitatio volcans venit. delerium. vobis', CAST(4639.53 AS Decimal(6, 2)), CAST(585.76 AS Decimal(6, 2)), 827),
        (70, N'Dairy', N'quorum novum pars quoque gravis travissimantor ut rarendum non pars sed in et fecit. travissimantor funem.', CAST(8874.99 AS Decimal(6, 2)), CAST(249.07 AS Decimal(6, 2)), 220),
        (71, N'Grain', N'in ut et estis quantare eggredior. quartu gravis volcans gravis venit. sed quad venit. et et dolorum', CAST(3682.73 AS Decimal(6, 2)), CAST(237.83 AS Decimal(6, 2)), 1000),
        (72, N'Snails', N'Longam, nomen nomen novum manifestum et quad in fecundio, non esset vantis. plurissimum Pro volcans fecundio, quo, quad Pro', CAST(2276.12 AS Decimal(6, 2)), CAST(2155.01 AS Decimal(6, 2)), 482),
        (73, N'Cereals', N'linguens quantare novum non et travissimantor dolorum quo, funem. quantare parte Longam, Quad regit,', CAST(4766.41 AS Decimal(6, 2)), CAST(9992.63 AS Decimal(6, 2)), 653),
        (74, N'Dairy', N'funem. si eudis imaginator egreddior gravum si travissimantor quoque glavans parte quis et quo non fecundio,', CAST(5505.15 AS Decimal(6, 2)), CAST(4259.64 AS Decimal(6, 2)), 720),
        (75, N'Grain', N'Tam in linguens quoque quo, et et trepicandor essit. rarendum si funem. transit. fecundio, et et plorum pladior', CAST(9666.97 AS Decimal(6, 2)), CAST(4189.52 AS Decimal(6, 2)), 810),
        (76, N'Cereals', N'sed quad quoque si Id estum. gravis nomen quad Sed fecundio, in vobis eggredior. linguens quo quad non', CAST(7994.43 AS Decimal(6, 2)), CAST(2245.86 AS Decimal(6, 2)), 101),
        (77, N'Meat', N'plorum quartu Et non novum plurissimum non plorum essit. et et in linguens quorum funem. Multum ut estis', CAST(3695.39 AS Decimal(6, 2)), CAST(4615.30 AS Decimal(6, 2)), 730),
        (78, N'Seafood', N'habitatio in Sed nomen quo cognitio, non e gravis in esset rarendum imaginator quantare non parte Longam, novum', CAST(7883.40 AS Decimal(6, 2)), CAST(4853.96 AS Decimal(6, 2)), 52),
        (79, N'Poultry', N'si parte vantis. quorum quoque et Longam, esset apparens Versus quoque cognitio, egreddior quad nomen', CAST(4295.55 AS Decimal(6, 2)), CAST(9355.84 AS Decimal(6, 2)), 126),
        (80, N'Shell fish', N'Longam, Tam Sed quad novum eggredior. plurissimum volcans novum Pro ut fecit, fecit. Versus si si linguens Pro bono estum.', CAST(1134.75 AS Decimal(6, 2)), CAST(5223.07 AS Decimal(6, 2)), 906),
        (81, N'Confections', N'Longam, nomen et manifestum estis si estum. volcans venit. quo, e linguens venit. quad trepicandor parte', CAST(3049.41 AS Decimal(6, 2)), CAST(992.39 AS Decimal(6, 2)), 190),
        (82, N'Meat', N'nomen apparens Versus quoque fecit, plorum plorum e venit. manifestum Pro ut quis si et in si plurissimum', CAST(7962.77 AS Decimal(6, 2)), CAST(9255.45 AS Decimal(6, 2)), 477),
        (83, N'Meat', N'linguens fecit. gravum regit, si e Multum in si Sed manifestum Multum quo Et sed homo, plorum homo, Quad', CAST(814.46 AS Decimal(6, 2)), CAST(9490.29 AS Decimal(6, 2)), 541),
        (84, N'Snails', N'manifestum quartu ut sed Sed non in et bono essit. vobis ut Longam, non gravum linguens rarendum Pro', CAST(4271.15 AS Decimal(6, 2)), CAST(4036.90 AS Decimal(6, 2)), 326),
        (85, N'Poultry', N'apparens pladior volcans Tam vobis in si imaginator si in parte quo rarendum Versus Versus vobis novum pars', CAST(2596.47 AS Decimal(6, 2)), CAST(5894.05 AS Decimal(6, 2)), 672),
        (86, N'Snails', N'et quantare si vantis. ut non e quo, essit. nomen Multum delerium. Versus in novum Multum non nomen nomen', NULL, CAST(7045.34 AS Decimal(6, 2)), 469),
        (87, N'Snails', N'ut et funem. Pro delerium. in egreddior delerium. quantare cognitio, glavans quad bono non non funem.', CAST(9002.25 AS Decimal(6, 2)), CAST(5667.23 AS Decimal(6, 2)), 834),
        (88, N'Poultry', N'travissimantor fecit, novum quad quoque homo, brevens, quad vantis. pladior quo novum quo quo, Id non', CAST(7860.56 AS Decimal(6, 2)), CAST(785.43 AS Decimal(6, 2)), 75),
        (89, N'Poultry', N'plurissimum funem. apparens linguens et gravis apparens plorum quartu quad brevens, cognitio, fecit, glavans e', CAST(300.74 AS Decimal(6, 2)), CAST(44.24 AS Decimal(6, 2)), 794),
        (90, N'Seafood', N'homo, in essit. quantare in in parte venit. funem. in et non novum quorum novum et linguens cognitio,', CAST(8801.46 AS Decimal(6, 2)), CAST(5133.67 AS Decimal(6, 2)), 765),
        (91, N'Produce', N'pladior quad plurissimum vobis regit, plurissimum essit. Id Tam linguens quis pladior funem. funem. vobis non', CAST(1795.83 AS Decimal(6, 2)), CAST(5490.23 AS Decimal(6, 2)), 938),
        (92, N'Seafood', N'estis brevens, habitatio vantis. fecit, plorum nomen et plorum si gravis quo, quartu egreddior gravum trepicandor', CAST(4412.77 AS Decimal(6, 2)), CAST(7983.28 AS Decimal(6, 2)), 295),
        (93, N'Dairy', N'eggredior. habitatio delerium. in egreddior in Tam gravis volcans funem. gravum Longam, transit. quis', CAST(6300.99 AS Decimal(6, 2)), CAST(7282.69 AS Decimal(6, 2)), 523),
        (94, N'Dairy', N'Longam, Pro brevens, estum. fecit, linguens non plurissimum travissimantor non non esset transit. nomen quis quoque', CAST(3196.21 AS Decimal(6, 2)), CAST(950.69 AS Decimal(6, 2)), 664),
        (95, N'Produce', N'habitatio in glavans Sed Et in et plurissimum si plurissimum gravum habitatio nomen estum. gravis pladior non gravum', CAST(1622.07 AS Decimal(6, 2)), CAST(4222.34 AS Decimal(6, 2)), 333),
        (96, N'Grain', N'pladior sed linguens non plurissimum Id quo, imaginator linguens volcans gravum et egreddior pars venit. quantare in', CAST(7321.20 AS Decimal(6, 2)), CAST(4111.33 AS Decimal(6, 2)), 287),
        (97, N'Cereals', N'vobis si Id volcans venit. si in delerium. Pro quo esset novum egreddior estis si linguens quoque regit,', CAST(8685.63 AS Decimal(6, 2)), CAST(8566.87 AS Decimal(6, 2)), 821),
        (98, N'Beverages', N'plorum et egreddior linguens essit. Id manifestum Sed quantare trepicandor habitatio vobis apparens non', CAST(4718.86 AS Decimal(6, 2)), CAST(8792.93 AS Decimal(6, 2)), 223),
        (99, N'Confections', N'transit. Tam sed quo quoque non vobis et homo, eudis novum habitatio linguens Versus essit. glavans novum', CAST(8043.34 AS Decimal(6, 2)), CAST(5916.94 AS Decimal(6, 2)), 187),
        (100, N'Produce', N'glavans Id Id gravis quo Et volcans dolorum manifestum non dolorum et essit. bono venit. e vobis quartu', CAST(6255.03 AS Decimal(6, 2)), CAST(9026.66 AS Decimal(6, 2)), 69)
GO

INSERT [dbo].[dishes] ([id], [name], [description], [base_price], [sale_price], [dish_type_id])
    VALUES
        (101, N'Meat', N'Quad quartu quo, egreddior fecundio, gravis Pro esset quorum travissimantor et gravum glavans Sed travissimantor non', CAST(4781.04 AS Decimal(6, 2)), CAST(9287.54 AS Decimal(6, 2)), 61),
        (102, N'Cereals', N'delerium. et delerium. vobis plorum quad non vobis egreddior quad plurissimum homo, travissimantor Quad', CAST(8487.54 AS Decimal(6, 2)), CAST(7316.50 AS Decimal(6, 2)), 694),
        (103, N'Dairy', N'novum et travissimantor imaginator novum quo, estum. estis et et si quad pladior non quad vantis. quartu non Longam, pladior eggredior. et plurissimum novum', CAST(4267.04 AS Decimal(6, 2)), CAST(5869.24 AS Decimal(6, 2)), 631),
        (104, N'Seafood', N'fecit. gravis Sed quo, Id dolorum et si non vobis non travissimantor essit. linguens quoque non quis fecit. manifestum parte venit. sed', CAST(538.09 AS Decimal(6, 2)), CAST(6277.67 AS Decimal(6, 2)), 928),
        (105, N'Produce', NULL, CAST(7423.35 AS Decimal(6, 2)), CAST(7505.16 AS Decimal(6, 2)), 50),
        (106, N'Meat', N'nomen Pro et gravis estis si Et gravum si manifestum apparens pars si si in fecit. venit. quantare non', CAST(1867.07 AS Decimal(6, 2)), CAST(5623.03 AS Decimal(6, 2)), 929),
        (107, N'Dairy', N'novum funem. novum Pro estum. manifestum novum fecit. Multum quoque eudis fecit, non homo, nomen linguens et linguens estum. non eudis Multum', CAST(4145.18 AS Decimal(6, 2)), CAST(740.60 AS Decimal(6, 2)), 67),
        (108, N'Shell fish', N'egreddior vobis quantare in eggredior. apparens e in et brevens, et quantare eudis Id quo, quartu eudis', CAST(1849.84 AS Decimal(6, 2)), CAST(7000.23 AS Decimal(6, 2)), 901),
        (109, N'Snails', N'brevens, nomen sed quad parte vobis eudis quoque e rarendum venit. Sed manifestum estis e quartu quo', CAST(721.07 AS Decimal(6, 2)), CAST(7329.97 AS Decimal(6, 2)), 679),
        (110, N'Shell fish', N'nomen et delerium. linguens funem. vobis quis manifestum apparens quad brevens, estum. quoque vobis cognitio, gravum delerium. et plorum quantare ut', CAST(4325.33 AS Decimal(6, 2)), CAST(8767.70 AS Decimal(6, 2)), 94),
        (111, N'Snails', N'quad novum Sed regit, si si Tam quartu funem. volcans e et funem. Et linguens Multum sed quartu nomen', CAST(1487.79 AS Decimal(6, 2)), CAST(7412.45 AS Decimal(6, 2)), 150),
        (112, N'Shell fish', N'quoque non eggredior. quantare estis et brevens, manifestum quo, brevens, quad habitatio eudis et Versus Id gravum', CAST(5315.87 AS Decimal(6, 2)), CAST(362.82 AS Decimal(6, 2)), 107),
        (113, N'Cereals', N'quantare non venit. volcans et fecit, si e esset Et pars nomen nomen trepicandor gravis novum Pro rarendum', CAST(1373.46 AS Decimal(6, 2)), CAST(2989.46 AS Decimal(6, 2)), 610),
        (114, N'Cereals', N'quis novum cognitio, et in in trepicandor quo, pars bono transit. estum. quad linguens et et quis et', CAST(9677.10 AS Decimal(6, 2)), CAST(4207.91 AS Decimal(6, 2)), 954),
        (115, N'Meat', N'venit. linguens Sed e Et Longam, estum. novum quoque pars parte et eudis e pladior apparens fecit. quo egreddior', CAST(7714.14 AS Decimal(6, 2)), CAST(9197.04 AS Decimal(6, 2)), 491),
        (116, N'Cereals', N'Longam, egreddior Et volcans esset novum essit. imaginator venit. et eudis plurissimum e vobis Sed gravis et volcans', CAST(5227.20 AS Decimal(6, 2)), CAST(1719.44 AS Decimal(6, 2)), 149),
        (117, N'Cereals', N'venit. e quad pars nomen regit, Multum quartu funem. plorum non travissimantor vantis. imaginator non', CAST(4143.63 AS Decimal(6, 2)), CAST(5776.94 AS Decimal(6, 2)), 19),
        (118, N'Produce', N'et bono quo non vantis. si cognitio, et fecundio, habitatio gravis quad parte novum et quantare non parte pladior parte linguens', CAST(19.11 AS Decimal(6, 2)), CAST(417.18 AS Decimal(6, 2)), 570),
        (119, N'Cereals', N'novum volcans parte fecit. vobis vobis fecit. linguens Sed quad homo, linguens linguens apparens novum et bono gravis ut', CAST(2711.60 AS Decimal(6, 2)), CAST(5735.03 AS Decimal(6, 2)), 226),
        (120, N'Shell fish', N'quad brevens, et quad gravum et estum. gravum nomen sed in ut non quartu et novum et estis gravis eudis', CAST(9602.91 AS Decimal(6, 2)), CAST(696.88 AS Decimal(6, 2)), 619),
        (121, N'Meat', N'Multum et Versus cognitio, quantare Tam novum vantis. vobis rarendum Tam in quantare brevens, regit, si', CAST(9443.26 AS Decimal(6, 2)), CAST(2155.74 AS Decimal(6, 2)), 6),
        (122, N'Beverages', N'linguens glavans Longam, non eggredior. nomen eudis parte quantare pars apparens delerium. funem. et', CAST(9885.92 AS Decimal(6, 2)), CAST(6359.12 AS Decimal(6, 2)), 361),
        (123, N'Grain', N'plurissimum quorum quo egreddior Tam fecit. in et et non non glavans et homo, in si gravis eggredior. cognitio, trepicandor glavans', CAST(2789.00 AS Decimal(6, 2)), CAST(1219.09 AS Decimal(6, 2)), 851),
        (124, N'Confections', N'dolorum in quantare novum eudis Quad quo estis quo, volcans gravis novum homo, quoque quad linguens linguens Et', CAST(4557.18 AS Decimal(6, 2)), CAST(5452.09 AS Decimal(6, 2)), 63),
        (125, N'Confections', N'brevens, quo, cognitio, parte essit. parte regit, Versus delerium. travissimantor non esset plorum et apparens', CAST(2843.70 AS Decimal(6, 2)), CAST(4758.83 AS Decimal(6, 2)), 282),
        (126, N'Seafood', N'fecit, fecundio, Longam, quad e quad quad Quad volcans Sed Multum quantare Versus funem. apparens manifestum', CAST(4462.22 AS Decimal(6, 2)), CAST(2254.55 AS Decimal(6, 2)), 705),
        (127, N'Snails', N'e ut apparens plorum Longam, non Sed venit. funem. manifestum imaginator quartu travissimantor quantare trepicandor quo', CAST(7381.74 AS Decimal(6, 2)), CAST(4872.31 AS Decimal(6, 2)), 959),
        (128, N'Cereals', N'egreddior nomen glavans vobis et nomen eudis quis funem. Pro nomen non esset volcans quad trepicandor Id', CAST(9079.90 AS Decimal(6, 2)), CAST(9041.93 AS Decimal(6, 2)), 34),
        (129, N'Seafood', N'brevens, pladior estis estum. quo quo, non gravum apparens rarendum nomen manifestum Multum esset Id Longam,', CAST(3144.33 AS Decimal(6, 2)), CAST(37.30 AS Decimal(6, 2)), 388),
        (130, N'Snails', N'nomen egreddior fecundio, novum et quartu glavans Quad quoque Tam parte quorum manifestum et trepicandor quo Versus', CAST(8183.95 AS Decimal(6, 2)), CAST(78.18 AS Decimal(6, 2)), 93),
        (131, N'Snails', N'gravis non novum rarendum parte fecit. rarendum fecit, apparens quoque Versus essit. in non rarendum', CAST(981.33 AS Decimal(6, 2)), CAST(3678.99 AS Decimal(6, 2)), 281),
        (132, N'Seafood', N'manifestum Quad plurissimum pladior regit, e plorum Multum trepicandor quartu gravum travissimantor gravum', CAST(3275.57 AS Decimal(6, 2)), CAST(5822.37 AS Decimal(6, 2)), 507),
        (133, N'Dairy', N'delerium. vantis. e vobis venit. vobis e linguens funem. Quad apparens et nomen Id Multum essit. et gravum quantare rarendum ut novum e quad', CAST(5652.05 AS Decimal(6, 2)), CAST(8937.01 AS Decimal(6, 2)), 532),
        (134, N'Produce', N'brevens, pladior trepicandor linguens quo, plorum estum. quoque pladior estum. travissimantor Id nomen', CAST(1628.36 AS Decimal(6, 2)), CAST(329.18 AS Decimal(6, 2)), 58),
        (135, N'Meat', N'nomen linguens quo transit. imaginator homo, transit. Pro fecit. et Et Sed quad non homo, quad Id e pladior', CAST(9514.51 AS Decimal(6, 2)), NULL, 131),
        (136, N'Poultry', N'gravis volcans Longam, fecit. e Longam, parte ut gravis non quad Quad travissimantor pars trepicandor', CAST(2647.20 AS Decimal(6, 2)), CAST(5935.53 AS Decimal(6, 2)), 497),
        (137, N'Seafood', N'estis e Quad trepicandor et essit. novum rarendum brevens, vantis. quorum et venit. quad egreddior vantis. fecit. Et gravum quantare', CAST(8782.36 AS Decimal(6, 2)), CAST(3675.88 AS Decimal(6, 2)), 847),
        (138, N'Dairy', N'manifestum plorum homo, Longam, et rarendum linguens Sed linguens linguens Quad si et Pro quorum et parte', CAST(7424.68 AS Decimal(6, 2)), CAST(3386.21 AS Decimal(6, 2)), 614),
        (139, N'Confections', N'homo, in ut brevens, vobis non in volcans gravis ut plorum Quad novum non plurissimum esset quoque e', CAST(3391.11 AS Decimal(6, 2)), CAST(3212.62 AS Decimal(6, 2)), 105),
        (140, N'Beverages', N'non ut cognitio, quo, e glavans non ut ut fecit, quad e funem. plorum quoque funem. plurissimum pars quo, bono Pro e', CAST(2404.08 AS Decimal(6, 2)), CAST(6531.74 AS Decimal(6, 2)), 743),
        (141, N'Shell fish', N'quartu dolorum quad gravum gravis estis venit. esset transit. quorum bono volcans gravis linguens non sed', CAST(8451.28 AS Decimal(6, 2)), CAST(271.02 AS Decimal(6, 2)), 402),
        (142, N'Dairy', N'volcans gravis esset Multum Longam, transit. fecundio, esset Pro quad manifestum plorum estum. Versus imaginator', CAST(7152.41 AS Decimal(6, 2)), CAST(6304.73 AS Decimal(6, 2)), 934),
        (143, N'Poultry', N'fecundio, fecit. pladior gravum ut Et Sed quoque linguens gravis fecit, habitatio e transit. et si glavans transit. non', CAST(7139.49 AS Decimal(6, 2)), CAST(8667.00 AS Decimal(6, 2)), 131),
        (144, N'Cereals', N'quad vantis. quartu non quad essit. quo, quantare parte essit. nomen glavans gravis fecundio, eggredior. esset', CAST(5975.41 AS Decimal(6, 2)), CAST(3455.46 AS Decimal(6, 2)), 25),
        (145, N'Meat', N'quo, Sed nomen Versus venit. quad et ut linguens quis regit, manifestum transit. regit, Quad novum essit.', CAST(7313.67 AS Decimal(6, 2)), CAST(1276.54 AS Decimal(6, 2)), 616),
        (146, N'Snails', N'pars pars Pro nomen vobis eggredior. habitatio vobis quad eudis delerium. quad Versus parte ut sed e Id plurissimum manifestum si Tam', CAST(6479.96 AS Decimal(6, 2)), CAST(7721.21 AS Decimal(6, 2)), 831),
        (147, N'Cereals', N'essit. quo trepicandor estis in quad quis et Longam, estis quad nomen Et vobis plorum quo, delerium. trepicandor', NULL, CAST(5127.40 AS Decimal(6, 2)), 686),
        (148, N'Seafood', N'e regit, linguens gravum novum et e et novum Id Longam, regit, essit. quorum e apparens imaginator Quad glavans', CAST(3039.30 AS Decimal(6, 2)), CAST(4993.82 AS Decimal(6, 2)), 118),
        (149, N'Grain', N'in gravis ut delerium. quo bono cognitio, manifestum novum et novum in trepicandor et Versus Et quad vobis si', CAST(6623.89 AS Decimal(6, 2)), CAST(3074.77 AS Decimal(6, 2)), 173),
        (150, N'Beverages', N'Longam, estum. plurissimum pars delerium. Multum dolorum et estis vobis glavans quad parte essit. travissimantor', CAST(5482.07 AS Decimal(6, 2)), NULL, 185),
        (151, N'Snails', N'quad Pro dolorum quantare Id quantare fecit. venit. trepicandor plorum quartu estis in in nomen dolorum', CAST(6394.87 AS Decimal(6, 2)), CAST(1753.64 AS Decimal(6, 2)), 113),
        (152, N'Shell fish', N'pladior quo glavans et trepicandor parte essit. pars linguens non homo, venit. sed egreddior quartu venit. delerium.', CAST(3177.56 AS Decimal(6, 2)), CAST(2502.89 AS Decimal(6, 2)), 251),
        (153, N'Meat', N'homo, bono novum Versus travissimantor Tam quad egreddior linguens plorum e bono parte plurissimum quad', CAST(8666.52 AS Decimal(6, 2)), CAST(8334.38 AS Decimal(6, 2)), 998),
        (154, N'Meat', N'plorum vantis. gravis vobis quad egreddior Versus pars Quad non transit. quad estis transit. quantare linguens rarendum vobis', CAST(2007.25 AS Decimal(6, 2)), CAST(8149.68 AS Decimal(6, 2)), 569),
        (155, N'Seafood', N'Multum pladior non pars plorum funem. bono quartu nomen quis plorum novum quo non Versus Longam, ut pladior apparens', CAST(8440.43 AS Decimal(6, 2)), CAST(3057.90 AS Decimal(6, 2)), 64),
        (156, N'Seafood', N'egreddior quo, plorum esset linguens quo quis Tam plorum et habitatio novum glavans et si quo, quo in', CAST(6811.77 AS Decimal(6, 2)), CAST(5220.05 AS Decimal(6, 2)), 264),
        (157, N'Dairy', N'gravis gravum Versus venit. cognitio, et homo, Quad novum travissimantor quantare homo, plurissimum Pro', CAST(4895.11 AS Decimal(6, 2)), CAST(6870.92 AS Decimal(6, 2)), 843),
        (158, N'Produce', N'quo trepicandor nomen quo, parte esset quo novum quo, et quo Id et egreddior in Pro Sed Quad cognitio, eggredior.', CAST(5698.54 AS Decimal(6, 2)), CAST(2928.41 AS Decimal(6, 2)), 154),
        (159, N'Dairy', N'quo non brevens, volcans Longam, Longam, sed fecit, quad sed pladior apparens venit. eudis et quis imaginator', CAST(9709.85 AS Decimal(6, 2)), CAST(6097.40 AS Decimal(6, 2)), 646),
        (160, N'Poultry', N'egreddior quorum apparens quad in gravum estum. estum. quis estum. e Versus vobis Longam, non essit. et Pro', CAST(7694.39 AS Decimal(6, 2)), CAST(417.15 AS Decimal(6, 2)), 517),
        (161, N'Poultry', N'rarendum quis novum homo, nomen delerium. fecit, Longam, esset glavans delerium. bono apparens brevens, essit. rarendum', CAST(2961.12 AS Decimal(6, 2)), CAST(1518.83 AS Decimal(6, 2)), 971),
        (162, N'Meat', N'homo, et egreddior non travissimantor rarendum et linguens novum e Et esset Id homo, non quad plorum trepicandor', CAST(4485.32 AS Decimal(6, 2)), CAST(5250.60 AS Decimal(6, 2)), 78),
        (163, N'Grain', N'fecit, et Tam non et quo fecit, Pro funem. fecit. Id Id vobis habitatio gravum quantare Multum esset delerium. fecundio, quo brevens, novum', CAST(5065.27 AS Decimal(6, 2)), CAST(750.71 AS Decimal(6, 2)), 513),
        (164, N'Dairy', N'gravis transit. trepicandor si fecit, plorum quoque fecit, et in parte Longam, in quoque non e Et et', CAST(8705.51 AS Decimal(6, 2)), CAST(1698.66 AS Decimal(6, 2)), 156),
        (165, N'Shell fish', N'e e quorum Sed et Longam, Versus gravis dolorum plorum pladior bono novum quo Pro volcans fecit. linguens', CAST(2537.11 AS Decimal(6, 2)), CAST(6962.93 AS Decimal(6, 2)), 814),
        (166, N'Grain', N'Et dolorum quad habitatio si nomen manifestum vobis imaginator quo manifestum gravis quorum bono homo, rarendum', CAST(3343.99 AS Decimal(6, 2)), CAST(7251.78 AS Decimal(6, 2)), 35),
        (167, N'Produce', N'estum. et Versus quoque novum in delerium. venit. vantis. fecundio, e manifestum esset quad et imaginator', CAST(8212.21 AS Decimal(6, 2)), CAST(5088.71 AS Decimal(6, 2)), 576),
        (168, N'Snails', N'et estis non e ut esset fecit. et et linguens non linguens transit. estis volcans pladior egreddior nomen', CAST(9663.82 AS Decimal(6, 2)), CAST(1590.08 AS Decimal(6, 2)), 553),
        (169, N'Seafood', N'venit. quoque venit. Longam, essit. fecundio, Multum quad Multum nomen et Versus linguens venit. quad', CAST(9745.10 AS Decimal(6, 2)), CAST(1425.81 AS Decimal(6, 2)), 673),
        (170, N'Snails', N'non fecundio, in rarendum linguens quoque trepicandor cognitio, trepicandor et glavans vantis. bono et', CAST(162.58 AS Decimal(6, 2)), CAST(2660.28 AS Decimal(6, 2)), 995),
        (171, N'Seafood', N'in gravum nomen in manifestum venit. estum. linguens essit. glavans glavans et vobis apparens nomen novum parte imaginator quad rarendum et pladior', CAST(5066.93 AS Decimal(6, 2)), CAST(8272.38 AS Decimal(6, 2)), 302),
        (172, N'Grain', N'quad plorum sed apparens trepicandor funem. brevens, non egreddior quo, linguens fecit. habitatio manifestum', CAST(6444.83 AS Decimal(6, 2)), CAST(5521.16 AS Decimal(6, 2)), 65),
        (173, N'Grain', N'quorum novum travissimantor glavans in non non et dolorum rarendum habitatio Multum Id bono plurissimum', CAST(6718.95 AS Decimal(6, 2)), CAST(8333.23 AS Decimal(6, 2)), 466),
        (174, N'Grain', N'cognitio, et plorum plurissimum essit. estum. Et nomen travissimantor quorum nomen estum. venit. quo regit,', CAST(6627.99 AS Decimal(6, 2)), CAST(2564.32 AS Decimal(6, 2)), 484),
        (175, N'Snails', N'manifestum pars et volcans ut manifestum et si fecit, imaginator cognitio, quo, sed brevens, e non novum', CAST(307.52 AS Decimal(6, 2)), CAST(3885.44 AS Decimal(6, 2)), 217),
        (176, N'Seafood', N'travissimantor nomen linguens vobis travissimantor fecit, et gravum non plorum fecit, si et habitatio', CAST(1151.62 AS Decimal(6, 2)), CAST(5464.01 AS Decimal(6, 2)), 72),
        (177, N'Grain', N'quo, novum pladior Sed vobis et Versus novum in manifestum sed Tam in nomen Versus parte parte si gravis', CAST(2290.85 AS Decimal(6, 2)), CAST(4392.15 AS Decimal(6, 2)), 231),
        (178, N'Snails', N'et quo, delerium. gravis Tam Quad quorum plorum quo, si vantis. ut homo, fecit, et et Et sed transit. pars vobis', CAST(2746.43 AS Decimal(6, 2)), CAST(3488.74 AS Decimal(6, 2)), 151),
        (179, N'Shell fish', N'nomen egreddior funem. et plorum imaginator e parte non novum trepicandor transit. esset eudis et egreddior fecit. cognitio, quorum', NULL, CAST(2903.66 AS Decimal(6, 2)), 447),
        (180, N'Seafood', N'quantare cognitio, imaginator quartu quad si et Sed et si Sed pladior in eudis in transit. gravis delerium.', CAST(6813.58 AS Decimal(6, 2)), CAST(9942.55 AS Decimal(6, 2)), 452),
        (181, N'Grain', N'imaginator in Sed nomen linguens fecit. Pro quad brevens, transit. plorum et quo Quad glavans gravum', CAST(7243.51 AS Decimal(6, 2)), CAST(7730.87 AS Decimal(6, 2)), 20),
        (182, N'Cereals', N'Quad eggredior. ut cognitio, pladior linguens gravis brevens, Tam Versus homo, manifestum novum fecit.', CAST(6363.73 AS Decimal(6, 2)), CAST(9631.42 AS Decimal(6, 2)), 389),
        (183, N'Dairy', N'pars si venit. pladior e et estis in non Pro trepicandor Sed sed plorum e plorum non Sed rarendum e linguens', CAST(1422.92 AS Decimal(6, 2)), CAST(7260.73 AS Decimal(6, 2)), 21),
        (184, N'Confections', N'quantare dolorum brevens, non quorum Quad et Multum e rarendum essit. venit. rarendum quantare estis', CAST(757.85 AS Decimal(6, 2)), CAST(1797.54 AS Decimal(6, 2)), 203),
        (185, N'Dairy', N'et egreddior venit. cognitio, imaginator estum. et plurissimum in vobis pars estum. trepicandor rarendum quis', CAST(3597.83 AS Decimal(6, 2)), CAST(7288.29 AS Decimal(6, 2)), 914),
        (186, N'Dairy', N'travissimantor bono manifestum plorum Versus essit. quis vantis. Tam quo, et novum nomen linguens esset quad Multum', CAST(6749.45 AS Decimal(6, 2)), CAST(7534.41 AS Decimal(6, 2)), 30),
        (187, N'Shell fish', N'gravis nomen non Sed quo apparens non bono dolorum plurissimum si quartu novum si parte novum gravis dolorum et', CAST(5006.39 AS Decimal(6, 2)), NULL, 510),
        (188, N'Cereals', N'esset eggredior. Id e Longam, quad Tam Id quo quis eudis funem. pars et Quad rarendum rarendum et quartu', CAST(2314.80 AS Decimal(6, 2)), CAST(1743.80 AS Decimal(6, 2)), 963),
        (189, N'Meat', N'quoque gravis bono quantare transit. eggredior. vantis. pladior pladior fecundio, novum non regit, essit. gravis', CAST(1268.31 AS Decimal(6, 2)), CAST(5529.30 AS Decimal(6, 2)), 994),
        (190, N'Beverages', N'habitatio non trepicandor linguens in non et sed plurissimum essit. et manifestum non transit. Sed quad essit.', CAST(7211.61 AS Decimal(6, 2)), CAST(2764.47 AS Decimal(6, 2)), 17),
        (191, N'Meat', N'plorum et funem. Id eudis eudis gravis et eggredior. pars vantis. si sed volcans et transit. et Multum', CAST(4816.59 AS Decimal(6, 2)), CAST(3716.95 AS Decimal(6, 2)), 654),
        (192, N'Poultry', N'in dolorum fecit. transit. fecit, quo, estum. esset quoque fecundio, linguens brevens, delerium. transit. quartu linguens linguens', CAST(4619.39 AS Decimal(6, 2)), CAST(3458.25 AS Decimal(6, 2)), 279),
        (193, N'Dairy', N'imaginator in imaginator esset quis egreddior quartu brevens, quoque Id esset eggredior. plorum quo gravis et', CAST(6948.66 AS Decimal(6, 2)), CAST(3007.11 AS Decimal(6, 2)), 968),
        (194, N'Produce', N'et ut et imaginator sed et quad quis quad fecit. fecit, gravis non manifestum brevens, Et parte Id eudis', CAST(9072.50 AS Decimal(6, 2)), CAST(7578.47 AS Decimal(6, 2)), 588),
        (195, N'Grain', N'et dolorum linguens et Id plorum pladior Quad pars trepicandor vobis Pro esset quartu novum cognitio, transit. estum.', CAST(9730.28 AS Decimal(6, 2)), CAST(2969.05 AS Decimal(6, 2)), 773),
        (196, N'Poultry', N'Id quis in dolorum non pars essit. e glavans apparens e Multum linguens manifestum Pro vantis. fecundio,', CAST(429.98 AS Decimal(6, 2)), CAST(1693.79 AS Decimal(6, 2)), 325),
        (197, N'Meat', N'si volcans quartu rarendum apparens et ut quartu Sed glavans si et brevens, pars novum non fecundio,', CAST(7918.75 AS Decimal(6, 2)), CAST(1281.13 AS Decimal(6, 2)), 421),
        (198, N'Poultry', N'et vobis parte funem. glavans eudis et estum. essit. si quantare transit. Longam, glavans pars non gravum cognitio,', CAST(3386.01 AS Decimal(6, 2)), CAST(9520.30 AS Decimal(6, 2)), 975),
        (199, N'Produce', N'pladior non quo, quorum brevens, et eggredior. quo gravis regit, rarendum nomen quad non parte et Sed Tam non', CAST(8446.89 AS Decimal(6, 2)), CAST(4606.06 AS Decimal(6, 2)), 886),
        (200, N'Produce', N'volcans quad eudis quad vobis cognitio, et in regit, pladior vobis Et cognitio, rarendum quantare e dolorum', CAST(4602.37 AS Decimal(6, 2)), CAST(1704.07 AS Decimal(6, 2)), 973)
GO

INSERT [dbo].[dishes] ([id], [name], [description], [base_price], [sale_price], [dish_type_id])
    VALUES
        (201, N'Confections', N'cognitio, plorum pladior delerium. delerium. sed parte funem. esset delerium. sed homo, et si habitatio trepicandor', CAST(2631.41 AS Decimal(6, 2)), CAST(6203.67 AS Decimal(6, 2)), 256),
        (202, N'Cereals', N'et quis nomen esset in e transit. vobis sed fecit. quad nomen manifestum quo nomen et quo pladior linguens', CAST(9101.45 AS Decimal(6, 2)), CAST(6187.83 AS Decimal(6, 2)), 133),
        (203, N'Dairy', N'glavans nomen Tam Versus linguens egreddior quad si non nomen plorum manifestum fecundio, gravis Pro', CAST(6816.13 AS Decimal(6, 2)), CAST(6131.13 AS Decimal(6, 2)), 898),
        (204, N'Cereals', N'manifestum quo volcans essit. delerium. funem. Id egreddior Longam, Longam, in non quad pars non si essit. quo', CAST(3294.20 AS Decimal(6, 2)), CAST(3701.59 AS Decimal(6, 2)), 179),
        (205, N'Produce', N'non dolorum gravis volcans novum non fecit, venit. Quad Tam quartu gravis non essit. Versus transit.', CAST(6461.30 AS Decimal(6, 2)), CAST(2333.53 AS Decimal(6, 2)), 883),
        (206, N'Seafood', N'vobis esset si nomen in et travissimantor quo nomen transit. in gravis venit. brevens, volcans Quad gravum pars', CAST(415.13 AS Decimal(6, 2)), CAST(4802.38 AS Decimal(6, 2)), 545),
        (207, N'Seafood', N'Id quis Multum eggredior. quis quad Pro delerium. rarendum essit. ut et trepicandor in Multum quo volcans habitatio', CAST(9950.03 AS Decimal(6, 2)), CAST(6232.48 AS Decimal(6, 2)), 786),
        (208, N'Shell fish', N'essit. linguens Id quo et linguens quad et brevens, non si linguens fecundio, plorum e habitatio plorum sed', CAST(6458.60 AS Decimal(6, 2)), CAST(4169.65 AS Decimal(6, 2)), 515),
        (209, N'Poultry', N'gravis fecit. Longam, venit. egreddior et Tam egreddior imaginator quo delerium. si Longam, cognitio, si Pro', CAST(2038.52 AS Decimal(6, 2)), CAST(5770.06 AS Decimal(6, 2)), 353),
        (210, N'Snails', N'quoque vobis eggredior. gravum dolorum estum. apparens quo pladior fecit, ut quad ut estis quad Id brevens, gravis', CAST(1699.73 AS Decimal(6, 2)), CAST(4264.24 AS Decimal(6, 2)), 23),
        (211, N'Produce', N'non Versus e habitatio si quad fecit, quantare in imaginator rarendum non trepicandor gravis quad et', CAST(7288.81 AS Decimal(6, 2)), CAST(7593.88 AS Decimal(6, 2)), 34),
        (212, N'Beverages', N'et dolorum esset quoque et quo fecundio, et travissimantor gravis quo quad cognitio, cognitio, vobis plurissimum', CAST(4520.91 AS Decimal(6, 2)), CAST(827.90 AS Decimal(6, 2)), 692),
        (213, N'Snails', N'Pro estum. et plurissimum et et funem. nomen eggredior. in nomen vantis. esset non plurissimum nomen quo plorum', CAST(2148.67 AS Decimal(6, 2)), CAST(3382.18 AS Decimal(6, 2)), 122),
        (214, N'Produce', N'gravis gravum quartu regit, quo novum quorum vantis. et novum trepicandor si Tam ut habitatio quad e', CAST(8884.95 AS Decimal(6, 2)), CAST(24.75 AS Decimal(6, 2)), 55),
        (215, N'Shell fish', N'imaginator imaginator quis travissimantor Pro funem. e sed essit. quo, travissimantor homo, ut eudis', CAST(2466.34 AS Decimal(6, 2)), CAST(6154.85 AS Decimal(6, 2)), 136),
        (216, N'Produce', N'Pro novum nomen pars habitatio fecundio, novum quo Multum non venit. Longam, imaginator quad quantare', CAST(1330.65 AS Decimal(6, 2)), CAST(2686.28 AS Decimal(6, 2)), 582),
        (217, N'Meat', N'manifestum imaginator gravum essit. Quad dolorum essit. plorum quad gravum si venit. linguens Quad ut', CAST(1538.20 AS Decimal(6, 2)), CAST(1887.40 AS Decimal(6, 2)), 262),
        (218, N'Meat', N'non volcans funem. Pro quoque fecit, trepicandor dolorum gravum eudis parte manifestum Quad si quo, e', CAST(3727.47 AS Decimal(6, 2)), CAST(7989.87 AS Decimal(6, 2)), 311),
        (219, N'Snails', N'si trepicandor Et bono quad manifestum ut venit. estis brevens, manifestum Tam quo transit. novum quantare', CAST(1467.43 AS Decimal(6, 2)), CAST(8953.17 AS Decimal(6, 2)), 243),
        (220, N'Shell fish', N'pladior quad quartu Multum sed fecundio, Et vobis estis funem. non fecit, e fecit. gravis in apparens quoque', CAST(1956.05 AS Decimal(6, 2)), CAST(4410.37 AS Decimal(6, 2)), 785),
        (221, N'Cereals', N'plorum non quad novum rarendum et eggredior. vantis. ut linguens eudis plorum quo vobis estum. vobis quo,', CAST(7530.72 AS Decimal(6, 2)), CAST(9428.51 AS Decimal(6, 2)), 134),
        (222, N'Beverages', N'pladior transit. novum transit. ut pladior quad estum. egreddior et estum. in quad sed quoque parte quoque glavans', CAST(1029.19 AS Decimal(6, 2)), CAST(5507.97 AS Decimal(6, 2)), 613),
        (223, N'Grain', N'regit, quad in in fecit, glavans et homo, Sed nomen Et volcans Multum quorum quad quad quad non Pro quo', CAST(6943.90 AS Decimal(6, 2)), CAST(9559.40 AS Decimal(6, 2)), 560),
        (224, N'Beverages', N'cognitio, et brevens, e regit, essit. brevens, glavans nomen Sed vobis regit, quad si quad estis et plurissimum quad', CAST(2452.21 AS Decimal(6, 2)), CAST(8825.61 AS Decimal(6, 2)), 656),
        (225, N'Poultry', N'habitatio et regit, quo in esset quoque et et travissimantor fecit. delerium. si gravis in linguens venit. plorum', CAST(4928.50 AS Decimal(6, 2)), CAST(7708.85 AS Decimal(6, 2)), 342),
        (226, N'Produce', N'in essit. Et parte delerium. gravis nomen Id imaginator et linguens si estum. apparens homo, homo, plorum venit.', CAST(5543.19 AS Decimal(6, 2)), CAST(9202.02 AS Decimal(6, 2)), 24),
        (227, N'Poultry', N'et quad sed rarendum non dolorum apparens quoque funem. pars linguens Pro vantis. esset et delerium.', CAST(8118.27 AS Decimal(6, 2)), CAST(5265.27 AS Decimal(6, 2)), 98),
        (228, N'Produce', N'quorum ut vobis Longam, quoque eggredior. gravum in Pro quo Multum quorum Quad e Multum funem. et quad apparens Versus Tam funem. egreddior', CAST(7372.32 AS Decimal(6, 2)), CAST(7942.68 AS Decimal(6, 2)), 878),
        (229, N'Snails', N'non estis egreddior Quad gravum Et et vobis linguens manifestum estum. linguens plorum vobis plurissimum', CAST(6988.67 AS Decimal(6, 2)), CAST(5364.18 AS Decimal(6, 2)), 711),
        (230, N'Poultry', N'fecit. transit. et novum Tam essit. e in quo, gravum brevens, regit, non fecundio, linguens Longam, quo si eudis quartu', CAST(6198.01 AS Decimal(6, 2)), CAST(870.53 AS Decimal(6, 2)), 893),
        (231, N'Shell fish', N'venit. gravis gravis Tam gravum vobis travissimantor e homo, nomen cognitio, Quad venit. e quantare linguens plorum', CAST(2388.77 AS Decimal(6, 2)), CAST(2604.30 AS Decimal(6, 2)), 652),
        (232, N'Beverages', N'transit. novum Et regit, e travissimantor quo, volcans Longam, et pars Tam vobis novum apparens quo imaginator fecit.', CAST(7765.60 AS Decimal(6, 2)), CAST(5943.70 AS Decimal(6, 2)), 201),
        (233, N'Beverages', N'quad quad glavans si plorum volcans habitatio linguens quoque brevens, linguens vobis homo, plorum manifestum', CAST(3843.95 AS Decimal(6, 2)), CAST(9786.08 AS Decimal(6, 2)), 265),
        (234, N'Beverages', N'nomen Et Id sed gravis gravis Longam, pars fecit. fecundio, quoque ut apparens delerium. esset e quoque Pro gravum venit.', CAST(8144.06 AS Decimal(6, 2)), CAST(1784.67 AS Decimal(6, 2)), 475),
        (235, N'Beverages', N'quad e Longam, Quad e linguens vobis novum rarendum pars plorum trepicandor habitatio e quartu gravum venit.', CAST(4182.17 AS Decimal(6, 2)), CAST(6699.98 AS Decimal(6, 2)), 196),
        (236, N'Snails', N'et Longam, regit, manifestum Pro non bono et e trepicandor non eggredior. gravis cognitio, plorum plorum quo quantare', CAST(8142.06 AS Decimal(6, 2)), CAST(3754.72 AS Decimal(6, 2)), 888),
        (237, N'Cereals', N'nomen et quartu homo, pars cognitio, non non imaginator vobis homo, et in estis quad plorum egreddior', CAST(9547.59 AS Decimal(6, 2)), CAST(1599.73 AS Decimal(6, 2)), 492),
        (238, N'Seafood', N'eggredior. essit. e essit. et cognitio, quartu apparens regit, nomen et quo estum. Pro travissimantor nomen', CAST(8128.71 AS Decimal(6, 2)), CAST(5929.83 AS Decimal(6, 2)), 638),
        (239, N'Meat', N'plorum gravis quo funem. Quad pladior nomen brevens, quantare non glavans fecundio, bono cognitio, estis Quad gravum', CAST(4296.55 AS Decimal(6, 2)), CAST(4927.19 AS Decimal(6, 2)), 320),
        (240, N'Cereals', N'Id imaginator venit. plorum venit. trepicandor pladior apparens e Sed travissimantor trepicandor vobis', CAST(3182.70 AS Decimal(6, 2)), CAST(6995.15 AS Decimal(6, 2)), 369),
        (241, N'Cereals', N'novum si plorum parte venit. trepicandor quis quorum si Multum sed sed habitatio estis manifestum quad', CAST(6799.42 AS Decimal(6, 2)), CAST(1055.81 AS Decimal(6, 2)), 245),
        (242, N'Dairy', N'in vobis et linguens funem. apparens nomen quad quoque Id estis glavans glavans novum rarendum et pladior', CAST(8547.78 AS Decimal(6, 2)), CAST(3364.76 AS Decimal(6, 2)), 18),
        (243, N'Beverages', N'si linguens cognitio, venit. brevens, et habitatio fecit. delerium. quad cognitio, quo, regit, quorum', CAST(276.28 AS Decimal(6, 2)), CAST(5973.74 AS Decimal(6, 2)), 611),
        (244, N'Meat', N'plurissimum et brevens, habitatio eudis plurissimum non fecundio, quartu non trepicandor e nomen e rarendum', CAST(9568.58 AS Decimal(6, 2)), CAST(1265.06 AS Decimal(6, 2)), 2),
        (245, N'Meat', N'vobis si manifestum estum. vobis quartu glavans et gravum funem. quo, et parte Tam estis sed esset et quorum volcans', CAST(9922.79 AS Decimal(6, 2)), CAST(5170.58 AS Decimal(6, 2)), 984),
        (246, N'Confections', N'quoque quo quorum non quoque plorum nomen plorum et Et si Tam regit, quoque travissimantor imaginator', CAST(295.67 AS Decimal(6, 2)), CAST(2889.05 AS Decimal(6, 2)), 962),
        (247, N'Grain', N'novum quoque egreddior Quad pladior e egreddior novum manifestum quad brevens, travissimantor parte pars et non dolorum Pro', CAST(2470.72 AS Decimal(6, 2)), CAST(76.07 AS Decimal(6, 2)), 158),
        (248, N'Seafood', N'glavans non brevens, e quo transit. parte fecit, trepicandor quad et homo, homo, homo, non quad dolorum delerium. Versus', CAST(8063.70 AS Decimal(6, 2)), CAST(2982.35 AS Decimal(6, 2)), 195),
        (249, N'Snails', N'quo egreddior quo bono linguens funem. e trepicandor pladior nomen pladior vobis regit, fecundio, plorum volcans', CAST(6606.16 AS Decimal(6, 2)), CAST(1423.62 AS Decimal(6, 2)), 92),
        (250, N'Shell fish', N'essit. pars in quorum ut Pro gravis quad Pro quo pars trepicandor si estis Multum transit. Et fecit.', CAST(8399.62 AS Decimal(6, 2)), CAST(282.77 AS Decimal(6, 2)), 191),
        (251, N'Dairy', N'venit. trepicandor novum parte transit. non regit, manifestum eudis quo regit, gravis et plurissimum', CAST(8891.77 AS Decimal(6, 2)), CAST(9806.38 AS Decimal(6, 2)), 124),
        (252, N'Dairy', N'volcans fecundio, et venit. Quad quad Et et fecundio, eggredior. in quo, si regit, Longam, regit, glavans', CAST(4191.27 AS Decimal(6, 2)), CAST(3291.25 AS Decimal(6, 2)), 111),
        (253, N'Poultry', N'venit. e gravis et ut in delerium. trepicandor non e et esset quo, vobis si non vantis. vantis. Tam travissimantor e', CAST(1918.57 AS Decimal(6, 2)), CAST(567.12 AS Decimal(6, 2)), 733),
        (254, N'Snails', N'si manifestum e estis Tam homo, quorum dolorum fecundio, et vobis venit. novum non nomen eggredior. travissimantor quoque quartu', CAST(6490.84 AS Decimal(6, 2)), CAST(195.69 AS Decimal(6, 2)), 102),
        (255, N'Dairy', N'linguens volcans delerium. vobis et pars homo, plorum gravum essit. imaginator fecit, vantis. non egreddior apparens sed plurissimum et parte essit. sed Id', CAST(7071.64 AS Decimal(6, 2)), CAST(2275.55 AS Decimal(6, 2)), 840),
        (256, N'Dairy', N'et quartu plurissimum et funem. si brevens, venit. rarendum travissimantor Id vantis. Longam, si quartu', CAST(1602.22 AS Decimal(6, 2)), CAST(695.70 AS Decimal(6, 2)), 166),
        (257, N'Dairy', N'fecundio, Pro et quartu apparens linguens delerium. Et gravis manifestum bono et quad novum quad in essit. quis', CAST(2157.54 AS Decimal(6, 2)), CAST(6628.43 AS Decimal(6, 2)), 573),
        (258, N'Shell fish', N'quo quad vobis imaginator transit. novum fecit, estis brevens, Et rarendum cognitio, fecit, et nomen novum', CAST(4363.92 AS Decimal(6, 2)), CAST(7305.52 AS Decimal(6, 2)), 242),
        (259, N'Confections', N'Sed habitatio quad quartu nomen egreddior travissimantor quorum ut novum habitatio vobis nomen quartu novum', CAST(8365.69 AS Decimal(6, 2)), CAST(5992.74 AS Decimal(6, 2)), 838),
        (260, N'Snails', N'Tam in habitatio quartu plorum plorum funem. novum Quad Sed Multum apparens sed trepicandor gravis plorum pladior', CAST(918.11 AS Decimal(6, 2)), CAST(3131.51 AS Decimal(6, 2)), 860),
        (261, N'Produce', N'gravis nomen fecit, Quad e habitatio fecit. essit. et sed Multum et vobis Pro Id in homo, gravum quoque', CAST(2296.85 AS Decimal(6, 2)), CAST(9537.10 AS Decimal(6, 2)), 448),
        (262, N'Poultry', N'dolorum gravis quorum quorum rarendum Pro novum rarendum et fecit, plorum travissimantor eggredior. e vobis', CAST(2577.70 AS Decimal(6, 2)), CAST(8289.79 AS Decimal(6, 2)), 45),
        (263, N'Shell fish', N'homo, fecit, apparens et trepicandor Pro quoque manifestum quo, esset regit, quantare pars Sed Multum', CAST(9469.93 AS Decimal(6, 2)), CAST(8805.47 AS Decimal(6, 2)), 804),
        (264, N'Snails', N'imaginator pladior estum. brevens, quantare transit. et vobis plorum delerium. Tam si Et quorum esset', CAST(5840.51 AS Decimal(6, 2)), CAST(4899.52 AS Decimal(6, 2)), 461),
        (265, N'Beverages', N'plorum in Id gravis e quoque quantare cognitio, Pro quartu quad regit, nomen plurissimum quad non Multum regit,', CAST(9310.96 AS Decimal(6, 2)), CAST(1659.94 AS Decimal(6, 2)), 341),
        (266, N'Grain', N'estis regit, habitatio si manifestum Pro quad Longam, Quad pladior esset trepicandor Id quad parte Tam', CAST(9523.20 AS Decimal(6, 2)), CAST(1650.17 AS Decimal(6, 2)), 779),
        (267, N'Dairy', N'fecit, sed funem. cognitio, Et essit. si in si et manifestum et quorum et quorum non habitatio Pro quis', CAST(676.96 AS Decimal(6, 2)), NULL, 427),
        (268, N'Produce', N'quo plorum quo, nomen gravis quad habitatio Et homo, regit, manifestum nomen plurissimum quartu gravis Multum', CAST(4004.61 AS Decimal(6, 2)), CAST(1041.81 AS Decimal(6, 2)), 648),
        (269, N'Cereals', N'quo et plorum novum et Versus funem. trepicandor imaginator eudis fecit, Multum quorum nomen quad et', CAST(4702.77 AS Decimal(6, 2)), CAST(1597.50 AS Decimal(6, 2)), 71),
        (270, N'Shell fish', N'nomen regit, apparens novum linguens gravis in egreddior plorum plorum egreddior fecundio, manifestum plorum', CAST(4324.27 AS Decimal(6, 2)), CAST(3324.77 AS Decimal(6, 2)), 609),
        (271, N'Beverages', N'estis volcans vantis. fecundio, gravis regit, et plurissimum venit. estis rarendum essit. gravis plurissimum', CAST(1783.05 AS Decimal(6, 2)), CAST(2400.13 AS Decimal(6, 2)), 90),
        (272, N'Dairy', N'egreddior rarendum gravis nomen delerium. et quad Et Id dolorum Quad sed pars manifestum pladior nomen', CAST(3409.48 AS Decimal(6, 2)), CAST(1086.54 AS Decimal(6, 2)), 624),
        (273, N'Dairy', N'delerium. e Longam, Tam quo quartu egreddior eudis e et essit. plurissimum non si et imaginator vobis', CAST(9430.92 AS Decimal(6, 2)), CAST(5957.57 AS Decimal(6, 2)), 991),
        (274, N'Seafood', N'linguens gravis bono linguens brevens, Id et vantis. volcans Et plorum quartu pars eudis et vobis et', CAST(8284.73 AS Decimal(6, 2)), CAST(3062.68 AS Decimal(6, 2)), 874),
        (275, N'Beverages', N'glavans eudis sed et delerium. regit, homo, apparens apparens regit, si quantare vobis dolorum non manifestum', CAST(5156.63 AS Decimal(6, 2)), CAST(1958.01 AS Decimal(6, 2)), 540),
        (276, N'Cereals', N'linguens gravum cognitio, rarendum Longam, gravis plurissimum parte in quorum estum. novum in eudis fecundio, et estis', CAST(8982.93 AS Decimal(6, 2)), CAST(3354.56 AS Decimal(6, 2)), 138),
        (277, N'Snails', N'ut egreddior fecit, et Versus plurissimum rarendum imaginator apparens si volcans Multum novum cognitio, e e', CAST(752.90 AS Decimal(6, 2)), CAST(6063.75 AS Decimal(6, 2)), 244),
        (278, N'Confections', N'venit. essit. si trepicandor parte gravis plorum novum novum et eudis egreddior fecit. brevens, bono', CAST(7375.32 AS Decimal(6, 2)), CAST(9534.23 AS Decimal(6, 2)), 558),
        (279, N'Produce', N'non delerium. in volcans habitatio fecit. estum. Versus cognitio, plorum nomen transit. vantis. si Et', CAST(2529.41 AS Decimal(6, 2)), CAST(8294.33 AS Decimal(6, 2)), 169),
        (280, N'Seafood', N'in bono quantare et vobis et Longam, quo, egreddior e novum glavans fecit, Sed plurissimum non plorum cognitio, sed gravis', CAST(4632.83 AS Decimal(6, 2)), CAST(3655.02 AS Decimal(6, 2)), 380),
        (281, N'Beverages', N'homo, Longam, vobis novum pladior in quad quad funem. non quo Versus vobis fecit. parte pladior vobis', CAST(3072.46 AS Decimal(6, 2)), CAST(4819.80 AS Decimal(6, 2)), 867),
        (282, N'Confections', N'homo, linguens parte et quorum quorum manifestum quo vobis Versus glavans vantis. e et non et quad linguens Et', CAST(54.57 AS Decimal(6, 2)), CAST(9125.94 AS Decimal(6, 2)), 84),
        (283, N'Shell fish', N'plorum pladior si si Sed e non plurissimum gravum estum. regit, quis novum bono plorum funem. non plorum rarendum', CAST(766.16 AS Decimal(6, 2)), CAST(2282.92 AS Decimal(6, 2)), 787),
        (284, N'Beverages', N'egreddior glavans Versus regit, quis plorum gravum egreddior brevens, in quo non quo, vobis esset dolorum', CAST(8589.04 AS Decimal(6, 2)), CAST(6519.06 AS Decimal(6, 2)), 520),
        (285, N'Meat', N'quad quad plorum Sed eggredior. quo non delerium. quad non regit, plorum et imaginator sed plorum cognitio,', CAST(7306.23 AS Decimal(6, 2)), CAST(5081.40 AS Decimal(6, 2)), 830),
        (286, N'Shell fish', N'essit. rarendum travissimantor Versus et pladior pars trepicandor plorum Tam Tam parte non Pro brevens, esset trepicandor', CAST(8197.49 AS Decimal(6, 2)), CAST(1064.14 AS Decimal(6, 2)), 542),
        (287, N'Grain', N'quo, gravis et dolorum funem. sed Quad plorum bono parte si delerium. egreddior si manifestum homo, Versus nomen', CAST(5847.03 AS Decimal(6, 2)), CAST(9313.04 AS Decimal(6, 2)), 130),
        (288, N'Beverages', N'si et transit. estum. vantis. vobis dolorum gravis quo non Tam eudis gravis habitatio travissimantor', CAST(7353.11 AS Decimal(6, 2)), CAST(5376.57 AS Decimal(6, 2)), 163),
        (289, N'Dairy', N'fecit. quo vobis Et in non funem. linguens vobis gravum fecit. quo fecit, quantare volcans quo pladior nomen', CAST(1072.41 AS Decimal(6, 2)), CAST(9590.38 AS Decimal(6, 2)), 635),
        (290, N'Dairy', N'delerium. cognitio, quorum Sed linguens si brevens, quis Tam homo, eudis vantis. quorum et pars gravis', CAST(2579.95 AS Decimal(6, 2)), CAST(9509.11 AS Decimal(6, 2)), 554),
        (291, N'Shell fish', N'vantis. vobis si plorum non funem. Tam apparens Versus non eggredior. non et delerium. plurissimum plorum cognitio,', CAST(5984.51 AS Decimal(6, 2)), CAST(6004.27 AS Decimal(6, 2)), 20),
        (292, N'Produce', N'fecundio, essit. linguens manifestum Longam, volcans Versus homo, Multum quo fecundio, manifestum Versus', CAST(5183.66 AS Decimal(6, 2)), CAST(7126.28 AS Decimal(6, 2)), 250),
        (293, N'Beverages', N'plorum fecit, rarendum eudis quad dolorum fecit, linguens eudis Tam trepicandor Quad esset quo Quad apparens plurissimum in', CAST(9763.02 AS Decimal(6, 2)), CAST(4294.21 AS Decimal(6, 2)), 801),
        (294, N'Meat', NULL, CAST(3378.43 AS Decimal(6, 2)), CAST(9937.08 AS Decimal(6, 2)), 264),
        (295, N'Shell fish', N'fecundio, fecit, habitatio delerium. nomen novum e Versus Longam, pars et travissimantor in parte bono', CAST(885.84 AS Decimal(6, 2)), CAST(1795.67 AS Decimal(6, 2)), 922),
        (296, N'Confections', N'habitatio glavans eudis Sed rarendum in delerium. Multum brevens, ut gravis Versus fecundio, vantis. transit. novum Id venit.', CAST(4221.71 AS Decimal(6, 2)), CAST(7458.04 AS Decimal(6, 2)), 47),
        (297, N'Beverages', N'e parte Tam cognitio, e rarendum plurissimum transit. apparens pars essit. estis Longam, quartu et Quad quoque gravum quantare imaginator', CAST(9077.85 AS Decimal(6, 2)), CAST(2766.01 AS Decimal(6, 2)), 193),
        (298, N'Beverages', N'nomen et sed pladior brevens, et nomen homo, et dolorum venit. estis apparens vobis novum quo novum venit. dolorum', CAST(4435.76 AS Decimal(6, 2)), CAST(4559.29 AS Decimal(6, 2)), 178),
        (299, N'Seafood', N'Tam novum habitatio manifestum nomen bono quad delerium. bono esset Et e quoque imaginator fecit. Et gravis gravis linguens', CAST(257.61 AS Decimal(6, 2)), CAST(1074.21 AS Decimal(6, 2)), 662),
        (300, N'Produce', N'quo venit. glavans vobis funem. egreddior glavans nomen quad pladior linguens in fecit, fecit, in habitatio pars brevens,', CAST(399.58 AS Decimal(6, 2)), CAST(9605.12 AS Decimal(6, 2)), 206)
GO

INSERT [dbo].[dishes] ([id], [name], [description], [base_price], [sale_price], [dish_type_id]) 
    VALUES 
        (301, N'Beverages', N'novum egreddior in Sed fecit, linguens in linguens non pars estis gravis apparens Quad eggredior. parte', CAST(9618.71 AS Decimal(6, 2)), CAST(3520.40 AS Decimal(6, 2)), 535),
        (302, N'Produce', N'manifestum quo si eggredior. Pro si Quad quad volcans essit. non parte Versus habitatio bono vantis.', CAST(8466.10 AS Decimal(6, 2)), CAST(1847.23 AS Decimal(6, 2)), 187),
        (303, N'Cereals', N'sed in parte imaginator novum parte parte novum vantis. eggredior. Pro Quad nomen dolorum novum quantare eggredior. quo pladior homo,', CAST(3360.92 AS Decimal(6, 2)), CAST(8478.56 AS Decimal(6, 2)), 774),
        (304, N'Dairy', N'vobis quo quantare vantis. novum rarendum in quad quad gravum cognitio, Id vobis Tam linguens si pars Versus esset quad vobis apparens Longam,', CAST(2281.89 AS Decimal(6, 2)), CAST(9657.57 AS Decimal(6, 2)), 483),
        (305, N'Cereals', N'eggredior. quo travissimantor transit. linguens et estis imaginator in et vobis e plurissimum in esset travissimantor delerium. delerium. si Tam', CAST(6616.57 AS Decimal(6, 2)), CAST(9023.48 AS Decimal(6, 2)), 254),
        (306, N'Dairy', N'gravum fecit. fecit. Quad novum quo parte parte quorum plurissimum nomen vobis et ut quo eudis parte novum', CAST(5482.28 AS Decimal(6, 2)), CAST(9196.23 AS Decimal(6, 2)), 439),
        (307, N'Dairy', N'estis e transit. quo, vobis et fecit, Versus sed in sed homo, fecundio, travissimantor Id linguens si', CAST(4760.34 AS Decimal(6, 2)), CAST(3848.81 AS Decimal(6, 2)), 120),
        (308, N'Confections', N'glavans venit. habitatio transit. Tam parte pladior plorum habitatio et cognitio, gravis non novum Sed', CAST(3633.83 AS Decimal(6, 2)), CAST(228.56 AS Decimal(6, 2)), 260),
        (309, N'Shell fish', N'ut quo, Et in et quo travissimantor non quad plurissimum quad quad quoque cognitio, quad transit. linguens', CAST(1334.20 AS Decimal(6, 2)), CAST(8609.11 AS Decimal(6, 2)), 563),
        (310, N'Meat', N'e essit. egreddior estis linguens quad quo fecundio, egreddior gravum trepicandor estis et venit. Pro', CAST(8088.71 AS Decimal(6, 2)), CAST(6841.13 AS Decimal(6, 2)), 703),
        (311, N'Beverages', N'bono et trepicandor nomen Id bono sed Longam, in gravis quartu Sed Id quo si travissimantor plorum venit. novum', CAST(849.31 AS Decimal(6, 2)), CAST(6211.80 AS Decimal(6, 2)), 641),
        (312, N'Shell fish', N'vobis e Pro delerium. et vobis essit. quad nomen Id travissimantor ut quad quad esset quo manifestum', CAST(4782.22 AS Decimal(6, 2)), CAST(1161.47 AS Decimal(6, 2)), 16),
        (313, N'Beverages', N'volcans apparens Tam quad novum et plurissimum plorum volcans Versus novum plorum venit. et quis fecit.', CAST(1834.51 AS Decimal(6, 2)), CAST(8334.09 AS Decimal(6, 2)), 148),
        (314, N'Snails', N'Et quo cognitio, apparens fecit, plurissimum estis essit. gravis quo si essit. delerium. Quad in plurissimum imaginator', CAST(3732.86 AS Decimal(6, 2)), CAST(3650.49 AS Decimal(6, 2)), 48),
        (315, N'Produce', N'trepicandor volcans quad e plurissimum ut et vobis si quo, gravis novum in eudis essit. quoque Id imaginator', CAST(7845.64 AS Decimal(6, 2)), CAST(1172.93 AS Decimal(6, 2)), 189),
        (316, N'Grain', N'quartu pladior et novum sed venit. brevens, in vobis vobis gravis manifestum et et e vobis quo, linguens quo et si', CAST(2242.28 AS Decimal(6, 2)), CAST(4005.56 AS Decimal(6, 2)), 123),
        (317, N'Grain', N'Id estum. novum volcans sed trepicandor esset estum. sed eggredior. quartu in fecundio, bono fecit. si quad', CAST(1811.54 AS Decimal(6, 2)), CAST(7254.18 AS Decimal(6, 2)), 121),
        (318, N'Produce', N'e cognitio, quad plorum quad volcans glavans delerium. quorum non regit, linguens non si brevens, quantare rarendum plorum', CAST(880.88 AS Decimal(6, 2)), CAST(1770.73 AS Decimal(6, 2)), 284),
        (319, N'Grain', N'trepicandor nomen sed imaginator egreddior quorum quo glavans glavans volcans gravis travissimantor pladior et in', CAST(8534.27 AS Decimal(6, 2)), CAST(3724.06 AS Decimal(6, 2)), 103),
        (320, N'Confections', N'transit. ut Longam, non fecundio, et venit. in Quad quartu manifestum et bono parte quoque nomen venit. bono Tam', CAST(1113.46 AS Decimal(6, 2)), CAST(3835.38 AS Decimal(6, 2)), 800),
        (321, N'Dairy', N'gravis homo, transit. et Pro quad quorum gravis quo plorum egreddior gravis estum. nomen parte estum.', CAST(3676.17 AS Decimal(6, 2)), CAST(2346.89 AS Decimal(6, 2)), 232),
        (322, N'Snails', N'regit, esset plorum non homo, manifestum quo et habitatio homo, venit. et quad pladior pars manifestum Versus', CAST(3323.84 AS Decimal(6, 2)), CAST(6273.60 AS Decimal(6, 2)), 156),
        (323, N'Produce', N'apparens regit, Quad quad Tam homo, travissimantor plorum travissimantor Et pars quad quad Versus et', CAST(2932.20 AS Decimal(6, 2)), CAST(1451.42 AS Decimal(6, 2)), 13),
        (324, N'Grain', N'fecit, habitatio e glavans pladior trepicandor quo pladior Et pars nomen linguens glavans cognitio, Versus', CAST(2122.81 AS Decimal(6, 2)), CAST(2088.39 AS Decimal(6, 2)), 446),
        (325, N'Snails', N'cognitio, delerium. plorum vobis estum. glavans quorum et et plorum Longam, Longam, quorum essit. quad plurissimum', CAST(8339.75 AS Decimal(6, 2)), CAST(7320.49 AS Decimal(6, 2)), 92),
        (326, N'Meat', N'in apparens fecit. quad et ut Tam vobis fecit. e quad estum. pladior Id quorum plorum plorum habitatio', CAST(6599.38 AS Decimal(6, 2)), CAST(5273.84 AS Decimal(6, 2)), 255),
        (327, N'Shell fish', N'quad pladior quantare fecit. cognitio, quo rarendum gravis Quad Pro non parte quad estis novum et quo,', CAST(3646.46 AS Decimal(6, 2)), CAST(6792.32 AS Decimal(6, 2)), 824),
        (328, N'Grain', N'rarendum plurissimum novum quantare esset venit. estis esset cognitio, glavans Longam, in et e quantare esset non', CAST(6052.48 AS Decimal(6, 2)), CAST(6020.48 AS Decimal(6, 2)), 531),
        (329, N'Meat', N'venit. vobis regit, Versus essit. apparens volcans rarendum Pro in homo, apparens quo estum. quo sed quorum et quo', CAST(7398.89 AS Decimal(6, 2)), CAST(1267.01 AS Decimal(6, 2)), 952),
        (330, N'Shell fish', N'imaginator vobis delerium. eggredior. brevens, vobis quoque quorum quo, gravis nomen quantare pladior cognitio, et et quo', CAST(934.91 AS Decimal(6, 2)), CAST(4499.97 AS Decimal(6, 2)), 184),
        (331, N'Poultry', N'homo, quo plurissimum novum nomen linguens non fecit. in si gravis Multum Sed gravis regit, quo imaginator', CAST(9905.07 AS Decimal(6, 2)), CAST(588.55 AS Decimal(6, 2)), 946),
        (332, N'Produce', N'et non sed quis quartu pars esset non pars in nomen gravum et novum novum quartu vobis estum. rarendum homo, vobis', CAST(6317.14 AS Decimal(6, 2)), CAST(1504.46 AS Decimal(6, 2)), 852),
        (333, N'Shell fish', N'sed si eggredior. delerium. novum nomen Quad fecundio, bono fecit, Longam, brevens, delerium. quoque', CAST(7117.70 AS Decimal(6, 2)), CAST(8460.01 AS Decimal(6, 2)), 64),
        (334, N'Dairy', N'egreddior dolorum et quo habitatio estum. quad estum. imaginator quorum funem. ut rarendum Longam, habitatio', CAST(2129.82 AS Decimal(6, 2)), CAST(8689.21 AS Decimal(6, 2)), 467),
        (335, N'Beverages', N'estum. Pro e plorum fecundio, manifestum quo plorum estum. si manifestum eggredior. vantis. nomen glavans', CAST(5014.11 AS Decimal(6, 2)), CAST(134.62 AS Decimal(6, 2)), 845),
        (336, N'Meat', N'et Versus estum. non Longam, egreddior manifestum quis delerium. pladior vobis si parte pars nomen quad essit. Pro', CAST(4606.36 AS Decimal(6, 2)), CAST(2972.56 AS Decimal(6, 2)), 357),
        (337, N'Grain', N'cognitio, plorum eudis esset linguens quad et quo estum. plorum fecit. nomen pladior in in fecundio, Pro', CAST(6693.64 AS Decimal(6, 2)), CAST(647.37 AS Decimal(6, 2)), 552),
        (338, N'Shell fish', N'fecit, estum. ut non quorum plorum linguens travissimantor quad Quad Tam et venit. quoque non essit.', CAST(8484.26 AS Decimal(6, 2)), CAST(2625.34 AS Decimal(6, 2)), 305),
        (339, N'Meat', N'egreddior apparens Tam esset e fecundio, non parte apparens fecit, quo, venit. Et in Sed nomen plorum funem.', CAST(1972.47 AS Decimal(6, 2)), CAST(7495.57 AS Decimal(6, 2)), 419),
        (340, N'Seafood', N'gravis quoque Multum in Tam vantis. rarendum e vobis cognitio, quo, habitatio egreddior plurissimum plurissimum', CAST(1823.95 AS Decimal(6, 2)), CAST(5885.17 AS Decimal(6, 2)), 391),
        (341, N'Shell fish', N'Quad gravis plurissimum non venit. gravis vobis travissimantor gravis et fecit. non apparens nomen brevens, Longam,', CAST(3437.15 AS Decimal(6, 2)), CAST(7215.33 AS Decimal(6, 2)), 422),
        (342, N'Meat', N'sed vantis. Tam rarendum quad si imaginator funem. plorum Quad egreddior volcans in regit, brevens, sed', CAST(2213.20 AS Decimal(6, 2)), CAST(9084.47 AS Decimal(6, 2)), 663),
        (343, N'Confections', N'apparens linguens nomen eudis Id regit, Et vobis estis homo, dolorum si trepicandor non delerium. non', CAST(6018.90 AS Decimal(6, 2)), CAST(6767.46 AS Decimal(6, 2)), 601),
        (344, N'Cereals', N'quad gravis fecit. transit. homo, dolorum homo, essit. et egreddior non sed esset gravum eudis glavans esset linguens', CAST(2983.70 AS Decimal(6, 2)), CAST(2749.25 AS Decimal(6, 2)), 932),
        (345, N'Shell fish', N'quantare Pro eggredior. novum estis Id pladior Longam, quis dolorum homo, quantare et non Sed esset glavans', CAST(1730.64 AS Decimal(6, 2)), CAST(3297.31 AS Decimal(6, 2)), 913),
        (346, N'Dairy', N'novum fecit, estis apparens rarendum si quoque glavans Longam, esset dolorum vobis apparens manifestum', CAST(1202.29 AS Decimal(6, 2)), CAST(4842.80 AS Decimal(6, 2)), 300),
        (347, N'Cereals', N'plurissimum pladior cognitio, egreddior manifestum eudis dolorum egreddior plorum vantis. fecit. et eudis', CAST(3349.15 AS Decimal(6, 2)), CAST(8792.19 AS Decimal(6, 2)), 681)
GO

